// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: role_binding.platform.proto

package v1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	v1 "chainguard.dev/sdk/proto/platform/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id, the UID of this role binding.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// identity, UID of the Identity to bind.
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// group, UIDP of the group to bind. This field is ignored and will be removed
	// in the future. The group is always the parent of the UIDP.
	//
	// Deprecated: Marked as deprecated in role_binding.platform.proto.
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	// role, UIDP of the Role to bind
	Role          string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	mi := &file_role_binding_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBinding) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// Deprecated: Marked as deprecated in role_binding.platform.proto.
func (x *RoleBinding) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RoleBinding) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RoleBindingList struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*RoleBindingList_Binding `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingList) Reset() {
	*x = RoleBindingList{}
	mi := &file_role_binding_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingList) ProtoMessage() {}

func (x *RoleBindingList) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBindingList.ProtoReflect.Descriptor instead.
func (*RoleBindingList) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{1}
}

func (x *RoleBindingList) GetItems() []*RoleBindingList_Binding {
	if x != nil {
		return x.Items
	}
	return nil
}

type RoleBindingFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the exact UID of the record.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// uidp filters records based on their position in the group hierarchy.
	Uidp          *v1.UIDPFilter `protobuf:"bytes,2,opt,name=uidp,proto3" json:"uidp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingFilter) Reset() {
	*x = RoleBindingFilter{}
	mi := &file_role_binding_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingFilter) ProtoMessage() {}

func (x *RoleBindingFilter) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBindingFilter.ProtoReflect.Descriptor instead.
func (*RoleBindingFilter) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{2}
}

func (x *RoleBindingFilter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBindingFilter) GetUidp() *v1.UIDPFilter {
	if x != nil {
		return x.Uidp
	}
	return nil
}

type CreateRoleBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent, The Group UIDP path under which the new RoleBinding resides.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// RoleBinding to create.
	RoleBinding   *RoleBinding `protobuf:"bytes,2,opt,name=role_binding,json=roleBinding,proto3" json:"role_binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleBindingRequest) Reset() {
	*x = CreateRoleBindingRequest{}
	mi := &file_role_binding_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleBindingRequest) ProtoMessage() {}

func (x *CreateRoleBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleBindingRequest) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleBindingRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateRoleBindingRequest) GetRoleBinding() *RoleBinding {
	if x != nil {
		return x.RoleBinding
	}
	return nil
}

type CreateRoleBindingBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent, The Group UIDP path under which the new RoleBinding resides.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// RoleBinding to create.
	RoleBindings  []*RoleBinding `protobuf:"bytes,2,rep,name=role_bindings,json=roleBindings,proto3" json:"role_bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleBindingBatchRequest) Reset() {
	*x = CreateRoleBindingBatchRequest{}
	mi := &file_role_binding_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleBindingBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleBindingBatchRequest) ProtoMessage() {}

func (x *CreateRoleBindingBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleBindingBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleBindingBatchRequest) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleBindingBatchRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateRoleBindingBatchRequest) GetRoleBindings() []*RoleBinding {
	if x != nil {
		return x.RoleBindings
	}
	return nil
}

type RoleBindingBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleBindings  []*RoleBinding         `protobuf:"bytes,1,rep,name=role_bindings,json=roleBindings,proto3" json:"role_bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBindingBatch) Reset() {
	*x = RoleBindingBatch{}
	mi := &file_role_binding_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingBatch) ProtoMessage() {}

func (x *RoleBindingBatch) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBindingBatch.ProtoReflect.Descriptor instead.
func (*RoleBindingBatch) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{5}
}

func (x *RoleBindingBatch) GetRoleBindings() []*RoleBinding {
	if x != nil {
		return x.RoleBindings
	}
	return nil
}

type DeleteRoleBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the exact UID of the record.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleBindingRequest) Reset() {
	*x = DeleteRoleBindingRequest{}
	mi := &file_role_binding_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleBindingRequest) ProtoMessage() {}

func (x *DeleteRoleBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleBindingRequest) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoleBindingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RoleBindingList_Binding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id, the UID of this role binding.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// group of the bound role.
	Group *Group `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// identity, UID of the Identity bound.
	Identity string `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	// role of the bound identity.
	Role *Role `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// verified email of the bound identity.
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// ClaimMatch issuer of the bound identity.
	ClaimMatchIssuer string `protobuf:"bytes,6,opt,name=claim_match_issuer,json=claimMatchIssuer,proto3" json:"claim_match_issuer,omitempty"`
	// ClaimMatch subject of the bound identity.
	ClaimMatchSubject string `protobuf:"bytes,7,opt,name=claim_match_subject,json=claimMatchSubject,proto3" json:"claim_match_subject,omitempty"`
	// created_at is the timestamp for when the role binding was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// unverified email of the bound identity.
	EmailUnverified string `protobuf:"bytes,9,opt,name=email_unverified,json=emailUnverified,proto3" json:"email_unverified,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoleBindingList_Binding) Reset() {
	*x = RoleBindingList_Binding{}
	mi := &file_role_binding_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBindingList_Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindingList_Binding) ProtoMessage() {}

func (x *RoleBindingList_Binding) ProtoReflect() protoreflect.Message {
	mi := &file_role_binding_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBindingList_Binding.ProtoReflect.Descriptor instead.
func (*RoleBindingList_Binding) Descriptor() ([]byte, []int) {
	return file_role_binding_platform_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RoleBindingList_Binding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBindingList_Binding) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *RoleBindingList_Binding) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *RoleBindingList_Binding) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleBindingList_Binding) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RoleBindingList_Binding) GetClaimMatchIssuer() string {
	if x != nil {
		return x.ClaimMatchIssuer
	}
	return ""
}

func (x *RoleBindingList_Binding) GetClaimMatchSubject() string {
	if x != nil {
		return x.ClaimMatchSubject
	}
	return ""
}

func (x *RoleBindingList_Binding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleBindingList_Binding) GetEmailUnverified() string {
	if x != nil {
		return x.EmailUnverified
	}
	return ""
}

var File_role_binding_platform_proto protoreflect.FileDescriptor

const file_role_binding_platform_proto_rawDesc = "" +
	"\n" +
	"\x1brole_binding.platform.proto\x12\x17chainguard.platform.iam\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16annotations/auth.proto\x1a\x18annotations/events.proto\x1a&platform/common/v1/uidp.platform.proto\x1a\x14group.platform.proto\x1a\x13role.platform.proto\"o\n" +
	"\vRoleBinding\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\x90\xaf\xa8\xd2\x05\x01R\x02id\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x18\n" +
	"\x05group\x18\x03 \x01(\tB\x02\x18\x01R\x05group\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xd4\x03\n" +
	"\x0fRoleBindingList\x12F\n" +
	"\x05items\x18\x01 \x03(\v20.chainguard.platform.iam.RoleBindingList.BindingR\x05items\x1a\xf8\x02\n" +
	"\aBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x05group\x18\x02 \x01(\v2\x1e.chainguard.platform.iam.GroupR\x05group\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x121\n" +
	"\x04role\x18\x04 \x01(\v2\x1d.chainguard.platform.iam.RoleR\x04role\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12,\n" +
	"\x12claim_match_issuer\x18\x06 \x01(\tR\x10claimMatchIssuer\x12.\n" +
	"\x13claim_match_subject\x18\a \x01(\tR\x11claimMatchSubject\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10email_unverified\x18\t \x01(\tR\x0femailUnverified\"_\n" +
	"\x11RoleBindingFilter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x04uidp\x18\x02 \x01(\v2&.chainguard.platform.common.UIDPFilterR\x04uidp\"\x83\x01\n" +
	"\x18CreateRoleBindingRequest\x12\x1e\n" +
	"\x06parent\x18\x01 \x01(\tB\x06\x90\xaf\xa8\xd2\x05\x01R\x06parent\x12G\n" +
	"\frole_binding\x18\x02 \x01(\v2$.chainguard.platform.iam.RoleBindingR\vroleBinding\"\x8a\x01\n" +
	"\x1dCreateRoleBindingBatchRequest\x12\x1e\n" +
	"\x06parent\x18\x01 \x01(\tB\x06\x90\xaf\xa8\xd2\x05\x01R\x06parent\x12I\n" +
	"\rrole_bindings\x18\x02 \x03(\v2$.chainguard.platform.iam.RoleBindingR\froleBindings\"]\n" +
	"\x10RoleBindingBatch\x12I\n" +
	"\rrole_bindings\x18\x01 \x03(\v2$.chainguard.platform.iam.RoleBindingR\froleBindings\"2\n" +
	"\x18DeleteRoleBindingRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\x90\xaf\xa8\xd2\x05\x01R\x02id2\x97\b\n" +
	"\fRoleBindings\x12\xe5\x01\n" +
	"\x06Create\x121.chainguard.platform.iam.CreateRoleBindingRequest\x1a$.chainguard.platform.iam.RoleBinding\"\x81\x01\x82\xd3\xe4\x93\x020:\frole_binding\" /iam/v1/rolebindings/{parent=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x91\x03\xc2\xf0\x8e\xfc\v9\n" +
	".dev.chainguard.api.iam.rolebindings.created.v1\x12\x05group\x18\x01\x12\x81\x02\n" +
	"\vCreateBatch\x126.chainguard.platform.iam.CreateRoleBindingBatchRequest\x1a).chainguard.platform.iam.RoleBindingBatch\"\x8e\x01\x82\xd3\xe4\x93\x027:\rrole_bindings\"&/iam/v1/rolebindings/batch/{parent=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x91\x03\xc2\xf0\x8e\xfc\v?\n" +
	"4dev.chainguard.api.iam.rolebindings.created.batch.v1\x12\x05group\x18\x01\x12\xc8\x01\n" +
	"\x06Update\x12$.chainguard.platform.iam.RoleBinding\x1a$.chainguard.platform.iam.RoleBinding\"r\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/iam/v1/rolebindings/{id=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x92\x03\xc2\xf0\x8e\xfc\v9\n" +
	".dev.chainguard.api.iam.rolebindings.updated.v1\x12\x05group\x18\x01\x12\x88\x01\n" +
	"\x04List\x12*.chainguard.platform.iam.RoleBindingFilter\x1a(.chainguard.platform.iam.RoleBindingList\"*\x82\xd3\xe4\x93\x02\x16\x12\x14/iam/v1/rolebindings\x8a\xaf\xa8\xd2\x05\b\x12\x06\n" +
	"\x02\x93\x03\x10\x01\x12\xc4\x01\n" +
	"\x06Delete\x121.chainguard.platform.iam.DeleteRoleBindingRequest\x1a\x16.google.protobuf.Empty\"o\x82\xd3\xe4\x93\x02\x1e*\x1c/iam/v1/rolebindings/{id=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x94\x03\xc2\xf0\x8e\xfc\v9\n" +
	".dev.chainguard.api.iam.rolebindings.deleted.v1\x12\x05group\x18\x01B*Z(chainguard.dev/sdk/proto/platform/iam/v1b\x06proto3"

var (
	file_role_binding_platform_proto_rawDescOnce sync.Once
	file_role_binding_platform_proto_rawDescData []byte
)

func file_role_binding_platform_proto_rawDescGZIP() []byte {
	file_role_binding_platform_proto_rawDescOnce.Do(func() {
		file_role_binding_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_binding_platform_proto_rawDesc), len(file_role_binding_platform_proto_rawDesc)))
	})
	return file_role_binding_platform_proto_rawDescData
}

var file_role_binding_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_role_binding_platform_proto_goTypes = []any{
	(*RoleBinding)(nil),                   // 0: chainguard.platform.iam.RoleBinding
	(*RoleBindingList)(nil),               // 1: chainguard.platform.iam.RoleBindingList
	(*RoleBindingFilter)(nil),             // 2: chainguard.platform.iam.RoleBindingFilter
	(*CreateRoleBindingRequest)(nil),      // 3: chainguard.platform.iam.CreateRoleBindingRequest
	(*CreateRoleBindingBatchRequest)(nil), // 4: chainguard.platform.iam.CreateRoleBindingBatchRequest
	(*RoleBindingBatch)(nil),              // 5: chainguard.platform.iam.RoleBindingBatch
	(*DeleteRoleBindingRequest)(nil),      // 6: chainguard.platform.iam.DeleteRoleBindingRequest
	(*RoleBindingList_Binding)(nil),       // 7: chainguard.platform.iam.RoleBindingList.Binding
	(*v1.UIDPFilter)(nil),                 // 8: chainguard.platform.common.UIDPFilter
	(*Group)(nil),                         // 9: chainguard.platform.iam.Group
	(*Role)(nil),                          // 10: chainguard.platform.iam.Role
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 12: google.protobuf.Empty
}
var file_role_binding_platform_proto_depIdxs = []int32{
	7,  // 0: chainguard.platform.iam.RoleBindingList.items:type_name -> chainguard.platform.iam.RoleBindingList.Binding
	8,  // 1: chainguard.platform.iam.RoleBindingFilter.uidp:type_name -> chainguard.platform.common.UIDPFilter
	0,  // 2: chainguard.platform.iam.CreateRoleBindingRequest.role_binding:type_name -> chainguard.platform.iam.RoleBinding
	0,  // 3: chainguard.platform.iam.CreateRoleBindingBatchRequest.role_bindings:type_name -> chainguard.platform.iam.RoleBinding
	0,  // 4: chainguard.platform.iam.RoleBindingBatch.role_bindings:type_name -> chainguard.platform.iam.RoleBinding
	9,  // 5: chainguard.platform.iam.RoleBindingList.Binding.group:type_name -> chainguard.platform.iam.Group
	10, // 6: chainguard.platform.iam.RoleBindingList.Binding.role:type_name -> chainguard.platform.iam.Role
	11, // 7: chainguard.platform.iam.RoleBindingList.Binding.created_at:type_name -> google.protobuf.Timestamp
	3,  // 8: chainguard.platform.iam.RoleBindings.Create:input_type -> chainguard.platform.iam.CreateRoleBindingRequest
	4,  // 9: chainguard.platform.iam.RoleBindings.CreateBatch:input_type -> chainguard.platform.iam.CreateRoleBindingBatchRequest
	0,  // 10: chainguard.platform.iam.RoleBindings.Update:input_type -> chainguard.platform.iam.RoleBinding
	2,  // 11: chainguard.platform.iam.RoleBindings.List:input_type -> chainguard.platform.iam.RoleBindingFilter
	6,  // 12: chainguard.platform.iam.RoleBindings.Delete:input_type -> chainguard.platform.iam.DeleteRoleBindingRequest
	0,  // 13: chainguard.platform.iam.RoleBindings.Create:output_type -> chainguard.platform.iam.RoleBinding
	5,  // 14: chainguard.platform.iam.RoleBindings.CreateBatch:output_type -> chainguard.platform.iam.RoleBindingBatch
	0,  // 15: chainguard.platform.iam.RoleBindings.Update:output_type -> chainguard.platform.iam.RoleBinding
	1,  // 16: chainguard.platform.iam.RoleBindings.List:output_type -> chainguard.platform.iam.RoleBindingList
	12, // 17: chainguard.platform.iam.RoleBindings.Delete:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_role_binding_platform_proto_init() }
func file_role_binding_platform_proto_init() {
	if File_role_binding_platform_proto != nil {
		return
	}
	file_group_platform_proto_init()
	file_role_platform_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_binding_platform_proto_rawDesc), len(file_role_binding_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_binding_platform_proto_goTypes,
		DependencyIndexes: file_role_binding_platform_proto_depIdxs,
		MessageInfos:      file_role_binding_platform_proto_msgTypes,
	}.Build()
	File_role_binding_platform_proto = out.File
	file_role_binding_platform_proto_goTypes = nil
	file_role_binding_platform_proto_depIdxs = nil
}
