// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: chainguard/platform/registry/v2beta1/repos.proto

package v2beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReposService_GetRepo_FullMethodName   = "/chainguard.platform.registry.v2beta1.ReposService/GetRepo"
	ReposService_ListRepos_FullMethodName = "/chainguard.platform.registry.v2beta1.ReposService/ListRepos"
)

// ReposServiceClient is the client API for ReposService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReposService manages Registry repositories.
type ReposServiceClient interface {
	// GetRepo retrieves a single repository by UID.
	GetRepo(ctx context.Context, in *GetRepoRequest, opts ...grpc.CallOption) (*Repo, error)
	// ListRepos returns repositories based on filter criteria with pagination support.
	ListRepos(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error)
}

type reposServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReposServiceClient(cc grpc.ClientConnInterface) ReposServiceClient {
	return &reposServiceClient{cc}
}

func (c *reposServiceClient) GetRepo(ctx context.Context, in *GetRepoRequest, opts ...grpc.CallOption) (*Repo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repo)
	err := c.cc.Invoke(ctx, ReposService_GetRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reposServiceClient) ListRepos(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposResponse)
	err := c.cc.Invoke(ctx, ReposService_ListRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReposServiceServer is the server API for ReposService service.
// All implementations must embed UnimplementedReposServiceServer
// for forward compatibility.
//
// ReposService manages Registry repositories.
type ReposServiceServer interface {
	// GetRepo retrieves a single repository by UID.
	GetRepo(context.Context, *GetRepoRequest) (*Repo, error)
	// ListRepos returns repositories based on filter criteria with pagination support.
	ListRepos(context.Context, *ListReposRequest) (*ListReposResponse, error)
	mustEmbedUnimplementedReposServiceServer()
}

// UnimplementedReposServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReposServiceServer struct{}

func (UnimplementedReposServiceServer) GetRepo(context.Context, *GetRepoRequest) (*Repo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepo not implemented")
}
func (UnimplementedReposServiceServer) ListRepos(context.Context, *ListReposRequest) (*ListReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepos not implemented")
}
func (UnimplementedReposServiceServer) mustEmbedUnimplementedReposServiceServer() {}
func (UnimplementedReposServiceServer) testEmbeddedByValue()                      {}

// UnsafeReposServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReposServiceServer will
// result in compilation errors.
type UnsafeReposServiceServer interface {
	mustEmbedUnimplementedReposServiceServer()
}

func RegisterReposServiceServer(s grpc.ServiceRegistrar, srv ReposServiceServer) {
	// If the following call panics, it indicates UnimplementedReposServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReposService_ServiceDesc, srv)
}

func _ReposService_GetRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReposServiceServer).GetRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReposService_GetRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReposServiceServer).GetRepo(ctx, req.(*GetRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReposService_ListRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReposServiceServer).ListRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReposService_ListRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReposServiceServer).ListRepos(ctx, req.(*ListReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReposService_ServiceDesc is the grpc.ServiceDesc for ReposService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReposService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.platform.registry.v2beta1.ReposService",
	HandlerType: (*ReposServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRepo",
			Handler:    _ReposService_GetRepo_Handler,
		},
		{
			MethodName: "ListRepos",
			Handler:    _ReposService_ListRepos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainguard/platform/registry/v2beta1/repos.proto",
}
