# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: github.com/aws/aws-sdk-go-v2

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
