// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: package_info.packages.platform.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackageInfo identifies one package and carries the policy-relevant facts
// about it.
//
// It lives here rather than beside either consumer because both the container
// and the library policy inputs carry a list of these, and a policy expression
// is written against the JSON shape rather than against a Go type. Two copies
// would let the shapes drift apart, and a policy that reads packages[].license
// would then mean different things depending on which side evaluated it.
type PackageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The PURL identifying the package: an APK for a container image
	// ("pkg:apk/wolfi/curl@8.11.0-r1?arch=x86_64"), or the version under
	// evaluation for a library ("pkg:npm/left-pad@1.3.0").
	Purl string `protobuf:"bytes,1,opt,name=purl,proto3" json:"purl,omitempty"`
	// The effective license, as an SPDX expression. Empty when unknown, which a
	// policy must treat as "no license claim" rather than as a permissive one.
	License       string `protobuf:"bytes,2,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_package_info_packages_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_package_info_packages_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_package_info_packages_platform_proto_rawDescGZIP(), []int{0}
}

func (x *PackageInfo) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *PackageInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

var File_package_info_packages_platform_proto protoreflect.FileDescriptor

const file_package_info_packages_platform_proto_rawDesc = "" +
	"\n" +
	"$package_info.packages.platform.proto\x12\x1cchainguard.platform.packages\";\n" +
	"\vPackageInfo\x12\x12\n" +
	"\x04purl\x18\x01 \x01(\tR\x04purl\x12\x18\n" +
	"\alicense\x18\x02 \x01(\tR\alicenseB/Z-chainguard.dev/sdk/proto/platform/packages/v1b\x06proto3"

var (
	file_package_info_packages_platform_proto_rawDescOnce sync.Once
	file_package_info_packages_platform_proto_rawDescData []byte
)

func file_package_info_packages_platform_proto_rawDescGZIP() []byte {
	file_package_info_packages_platform_proto_rawDescOnce.Do(func() {
		file_package_info_packages_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_package_info_packages_platform_proto_rawDesc), len(file_package_info_packages_platform_proto_rawDesc)))
	})
	return file_package_info_packages_platform_proto_rawDescData
}

var file_package_info_packages_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_package_info_packages_platform_proto_goTypes = []any{
	(*PackageInfo)(nil), // 0: chainguard.platform.packages.PackageInfo
}
var file_package_info_packages_platform_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_package_info_packages_platform_proto_init() }
func file_package_info_packages_platform_proto_init() {
	if File_package_info_packages_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_package_info_packages_platform_proto_rawDesc), len(file_package_info_packages_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_package_info_packages_platform_proto_goTypes,
		DependencyIndexes: file_package_info_packages_platform_proto_depIdxs,
		MessageInfos:      file_package_info_packages_platform_proto_msgTypes,
	}.Build()
	File_package_info_packages_platform_proto = out.File
	file_package_info_packages_platform_proto_goTypes = nil
	file_package_info_packages_platform_proto_depIdxs = nil
}
