// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: notifications.platform.proto

package v1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationsFilter_Location int32

const (
	// The "unset" value.
	NotificationsFilter_UNSPECIFIED NotificationsFilter_Location = 0
	// Console.
	NotificationsFilter_CONSOLE NotificationsFilter_Location = 1
	// Directory.
	NotificationsFilter_DIRECTORY NotificationsFilter_Location = 2
	// Chainctl.
	NotificationsFilter_CHAINCTL NotificationsFilter_Location = 3
)

// Enum value maps for NotificationsFilter_Location.
var (
	NotificationsFilter_Location_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CONSOLE",
		2: "DIRECTORY",
		3: "CHAINCTL",
	}
	NotificationsFilter_Location_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CONSOLE":     1,
		"DIRECTORY":   2,
		"CHAINCTL":    3,
	}
)

func (x NotificationsFilter_Location) Enum() *NotificationsFilter_Location {
	p := new(NotificationsFilter_Location)
	*p = x
	return p
}

func (x NotificationsFilter_Location) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationsFilter_Location) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_platform_proto_enumTypes[0].Descriptor()
}

func (NotificationsFilter_Location) Type() protoreflect.EnumType {
	return &file_notifications_platform_proto_enumTypes[0]
}

func (x NotificationsFilter_Location) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationsFilter_Location.Descriptor instead.
func (NotificationsFilter_Location) EnumDescriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{5, 0}
}

type NotificationsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Notification        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationsList) Reset() {
	*x = NotificationsList{}
	mi := &file_notifications_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationsList) ProtoMessage() {}

func (x *NotificationsList) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationsList.ProtoReflect.Descriptor instead.
func (*NotificationsList) Descriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationsList) GetItems() []*Notification {
	if x != nil {
		return x.Items
	}
	return nil
}

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the identifier of this specific notification.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// when the notification was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// when the notification was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// id of the category the notification belongs to.
	CategoryId string `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// subject or title of the notification.
	Subject string `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	// the body of the notification.
	Note string `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	// date when the notification was created.
	NoteDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=note_date,json=noteDate,proto3" json:"note_date,omitempty"`
	// tags associated with the notification.
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// account associated with the notification.
	Account *Account `protobuf:"bytes,9,opt,name=account,proto3" json:"account,omitempty"`
	// author associated with the notification.
	Author *Author `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	// account id associated with the notification.
	AccountId string `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// author id associated with the notification.
	AuthorId string `protobuf:"bytes,12,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// traits associated with the notification.
	Traits        *Traits `protobuf:"bytes,13,opt,name=traits,proto3" json:"traits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Notification) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Notification) GetNoteDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NoteDate
	}
	return nil
}

func (x *Notification) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Notification) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Notification) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Notification) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Notification) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Notification) GetTraits() *Traits {
	if x != nil {
		return x.Traits
	}
	return nil
}

type Traits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expiration date of the notification.
	Expires *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires,proto3" json:"expires,omitempty"`
	// show notification in console.
	Console bool `protobuf:"varint,2,opt,name=console,proto3" json:"console,omitempty"`
	// show notification in directory.
	Directory bool `protobuf:"varint,3,opt,name=directory,proto3" json:"directory,omitempty"`
	// start date of the notification.
	Starts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts,proto3" json:"starts,omitempty"`
	// whether or not notification has been approved.
	Approved bool `protobuf:"varint,5,opt,name=approved,proto3" json:"approved,omitempty"`
	// show notification for chainctl users.
	Chainctl      bool `protobuf:"varint,6,opt,name=chainctl,proto3" json:"chainctl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traits) Reset() {
	*x = Traits{}
	mi := &file_notifications_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traits) ProtoMessage() {}

func (x *Traits) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traits.ProtoReflect.Descriptor instead.
func (*Traits) Descriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{2}
}

func (x *Traits) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *Traits) GetConsole() bool {
	if x != nil {
		return x.Console
	}
	return false
}

func (x *Traits) GetDirectory() bool {
	if x != nil {
		return x.Directory
	}
	return false
}

func (x *Traits) GetStarts() *timestamppb.Timestamp {
	if x != nil {
		return x.Starts
	}
	return nil
}

func (x *Traits) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *Traits) GetChainctl() bool {
	if x != nil {
		return x.Chainctl
	}
	return false
}

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// when the account was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// when the account was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// name of the account.
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_notifications_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Author struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the author.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name of the author.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// email of the author.
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_notifications_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{4}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NotificationsFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the notification.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Location of where notifications are displayed.
	Location      NotificationsFilter_Location `protobuf:"varint,2,opt,name=location,proto3,enum=chainguard.platform.notifications.NotificationsFilter_Location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationsFilter) Reset() {
	*x = NotificationsFilter{}
	mi := &file_notifications_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationsFilter) ProtoMessage() {}

func (x *NotificationsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationsFilter.ProtoReflect.Descriptor instead.
func (*NotificationsFilter) Descriptor() ([]byte, []int) {
	return file_notifications_platform_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationsFilter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationsFilter) GetLocation() NotificationsFilter_Location {
	if x != nil {
		return x.Location
	}
	return NotificationsFilter_UNSPECIFIED
}

var File_notifications_platform_proto protoreflect.FileDescriptor

const file_notifications_platform_proto_rawDesc = "" +
	"\n" +
	"\x1cnotifications.platform.proto\x12!chainguard.platform.notifications\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16annotations/auth.proto\"Z\n" +
	"\x11NotificationsList\x12E\n" +
	"\x05items\x18\x01 \x03(\v2/.chainguard.platform.notifications.NotificationR\x05items\"\xb8\x04\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x127\n" +
	"\tnote_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bnoteDate\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12D\n" +
	"\aaccount\x18\t \x01(\v2*.chainguard.platform.notifications.AccountR\aaccount\x12A\n" +
	"\x06author\x18\n" +
	" \x01(\v2).chainguard.platform.notifications.AuthorR\x06author\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountId\x12\x1b\n" +
	"\tauthor_id\x18\f \x01(\tR\bauthorId\x12A\n" +
	"\x06traits\x18\r \x01(\v2).chainguard.platform.notifications.TraitsR\x06traits\"\xe2\x01\n" +
	"\x06Traits\x124\n" +
	"\aexpires\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\x12\x18\n" +
	"\aconsole\x18\x02 \x01(\bR\aconsole\x12\x1c\n" +
	"\tdirectory\x18\x03 \x01(\bR\tdirectory\x122\n" +
	"\x06starts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06starts\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\bR\bapproved\x12\x1a\n" +
	"\bchainctl\x18\x06 \x01(\bR\bchainctl\"\xa3\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"B\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xc9\x01\n" +
	"\x13NotificationsFilter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12[\n" +
	"\blocation\x18\x02 \x01(\x0e2?.chainguard.platform.notifications.NotificationsFilter.LocationR\blocation\"E\n" +
	"\bLocation\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aCONSOLE\x10\x01\x12\r\n" +
	"\tDIRECTORY\x10\x02\x12\f\n" +
	"\bCHAINCTL\x10\x032\xbe\x01\n" +
	"\rNotifications\x12\xac\x01\n" +
	"\x04List\x126.chainguard.platform.notifications.NotificationsFilter\x1a4.chainguard.platform.notifications.NotificationsList\"6\x82\xd3\xe4\x93\x02!\x12\x1f/notifications/v1/notifications\x8a\xaf\xa8\xd2\x05\t\x12\a\n" +
	"\x03g\xc5\f\x10\x01B4Z2chainguard.dev/sdk/proto/platform/notifications/v1b\x06proto3"

var (
	file_notifications_platform_proto_rawDescOnce sync.Once
	file_notifications_platform_proto_rawDescData []byte
)

func file_notifications_platform_proto_rawDescGZIP() []byte {
	file_notifications_platform_proto_rawDescOnce.Do(func() {
		file_notifications_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_platform_proto_rawDesc), len(file_notifications_platform_proto_rawDesc)))
	})
	return file_notifications_platform_proto_rawDescData
}

var file_notifications_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notifications_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notifications_platform_proto_goTypes = []any{
	(NotificationsFilter_Location)(0), // 0: chainguard.platform.notifications.NotificationsFilter.Location
	(*NotificationsList)(nil),         // 1: chainguard.platform.notifications.NotificationsList
	(*Notification)(nil),              // 2: chainguard.platform.notifications.Notification
	(*Traits)(nil),                    // 3: chainguard.platform.notifications.Traits
	(*Account)(nil),                   // 4: chainguard.platform.notifications.Account
	(*Author)(nil),                    // 5: chainguard.platform.notifications.Author
	(*NotificationsFilter)(nil),       // 6: chainguard.platform.notifications.NotificationsFilter
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
}
var file_notifications_platform_proto_depIdxs = []int32{
	2,  // 0: chainguard.platform.notifications.NotificationsList.items:type_name -> chainguard.platform.notifications.Notification
	7,  // 1: chainguard.platform.notifications.Notification.created_at:type_name -> google.protobuf.Timestamp
	7,  // 2: chainguard.platform.notifications.Notification.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 3: chainguard.platform.notifications.Notification.note_date:type_name -> google.protobuf.Timestamp
	4,  // 4: chainguard.platform.notifications.Notification.account:type_name -> chainguard.platform.notifications.Account
	5,  // 5: chainguard.platform.notifications.Notification.author:type_name -> chainguard.platform.notifications.Author
	3,  // 6: chainguard.platform.notifications.Notification.traits:type_name -> chainguard.platform.notifications.Traits
	7,  // 7: chainguard.platform.notifications.Traits.expires:type_name -> google.protobuf.Timestamp
	7,  // 8: chainguard.platform.notifications.Traits.starts:type_name -> google.protobuf.Timestamp
	7,  // 9: chainguard.platform.notifications.Account.created_at:type_name -> google.protobuf.Timestamp
	7,  // 10: chainguard.platform.notifications.Account.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: chainguard.platform.notifications.NotificationsFilter.location:type_name -> chainguard.platform.notifications.NotificationsFilter.Location
	6,  // 12: chainguard.platform.notifications.Notifications.List:input_type -> chainguard.platform.notifications.NotificationsFilter
	1,  // 13: chainguard.platform.notifications.Notifications.List:output_type -> chainguard.platform.notifications.NotificationsList
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_notifications_platform_proto_init() }
func file_notifications_platform_proto_init() {
	if File_notifications_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_platform_proto_rawDesc), len(file_notifications_platform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_platform_proto_goTypes,
		DependencyIndexes: file_notifications_platform_proto_depIdxs,
		EnumInfos:         file_notifications_platform_proto_enumTypes,
		MessageInfos:      file_notifications_platform_proto_msgTypes,
	}.Build()
	File_notifications_platform_proto = out.File
	file_notifications_platform_proto_goTypes = nil
	file_notifications_platform_proto_depIdxs = nil
}
