// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: chainguard/platform/iam/v2beta1/identity_providers.proto

package v2beta1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	v1 "chainguard.dev/sdk/proto/platform/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentityProvider represents the configuration parameters necessary for performing
// authentication with an upstream identity provider.
type IdentityProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the identity provider (UIDP).
	// Generated by server.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Human-readable name of the identity provider.
	// Must be 3-63 characters.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description of the identity provider.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// When the identity provider was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When the identity provider was last updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The UIDP of the default role to grant users of this identity provider
	// on initial authentication. Users who already have an identity on this platform
	// are unaffected.
	DefaultRole string `protobuf:"bytes,6,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
	// The upstream IdP configuration details for this identity provider.
	// Exactly one must be set.
	//
	// Types that are valid to be assigned to Configuration:
	//
	//	*IdentityProvider_Oidc
	Configuration isIdentityProvider_Configuration `protobuf_oneof:"configuration"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityProvider) Reset() {
	*x = IdentityProvider{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProvider) ProtoMessage() {}

func (x *IdentityProvider) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProvider.ProtoReflect.Descriptor instead.
func (*IdentityProvider) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityProvider) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *IdentityProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentityProvider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IdentityProvider) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *IdentityProvider) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *IdentityProvider) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

func (x *IdentityProvider) GetConfiguration() isIdentityProvider_Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *IdentityProvider) GetOidc() *IdentityProvider_OIDC {
	if x != nil {
		if x, ok := x.Configuration.(*IdentityProvider_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

type isIdentityProvider_Configuration interface {
	isIdentityProvider_Configuration()
}

type IdentityProvider_Oidc struct {
	// Defines the parameters necessary for authenticating with the OIDC flow.
	Oidc *IdentityProvider_OIDC `protobuf:"bytes,20,opt,name=oidc,proto3,oneof"`
}

func (*IdentityProvider_Oidc) isIdentityProvider_Configuration() {}

// ListIdentityProvidersRequest is the request message for ListIdentityProviders
type ListIdentityProvidersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter records based on their position in the group hierarchy.
	Uidp *v1.UIDPFilter `protobuf:"bytes,1,opt,name=uidp,proto3" json:"uidp,omitempty"`
	// Exact match on identity provider name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Maximum number of results to return per page.
	// Default: 50, Maximum: 200.
	PageSize int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token from a previous List response for pagination.
	// Opaque token with 3-day expiration.
	PageToken string `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Order results by field. Format: "field [asc|desc]"
	// Default: "uid asc"
	// Note: Changing order_by between pages invalidates the page token.
	OrderBy string `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Number of results to skip before returning.
	// Used for random-access pagination (jumping to arbitrary pages).
	// Can be combined with page_token to skip from cursor position.
	// Must be non-negative.
	Skip          int32 `protobuf:"varint,13,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentityProvidersRequest) Reset() {
	*x = ListIdentityProvidersRequest{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentityProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentityProvidersRequest) ProtoMessage() {}

func (x *ListIdentityProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentityProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListIdentityProvidersRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{1}
}

func (x *ListIdentityProvidersRequest) GetUidp() *v1.UIDPFilter {
	if x != nil {
		return x.Uidp
	}
	return nil
}

func (x *ListIdentityProvidersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListIdentityProvidersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIdentityProvidersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListIdentityProvidersRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListIdentityProvidersRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// ListIdentityProvidersResponse is the response message for ListIdentityProviders
type ListIdentityProvidersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity providers matching the filter criteria.
	IdentityProviders []*IdentityProvider `protobuf:"bytes,1,rep,name=identity_providers,json=identityProviders,proto3" json:"identity_providers,omitempty"`
	// Token for retrieving the next page of results.
	// Empty if no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of results matching the filter.
	// Optional, provided for UI pagination.
	TotalCount *int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	// Number of results that were skipped.
	// Accumulates across paginated requests.
	Skipped       int32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentityProvidersResponse) Reset() {
	*x = ListIdentityProvidersResponse{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentityProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentityProvidersResponse) ProtoMessage() {}

func (x *ListIdentityProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentityProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListIdentityProvidersResponse) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{2}
}

func (x *ListIdentityProvidersResponse) GetIdentityProviders() []*IdentityProvider {
	if x != nil {
		return x.IdentityProviders
	}
	return nil
}

func (x *ListIdentityProvidersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListIdentityProvidersResponse) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

func (x *ListIdentityProvidersResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

// GetIdentityProviderRequest is the request message for GetIdentityProvider
type GetIdentityProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID of the identity provider to retrieve.
	Uid           string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityProviderRequest) Reset() {
	*x = GetIdentityProviderRequest{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityProviderRequest) ProtoMessage() {}

func (x *GetIdentityProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityProviderRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{3}
}

func (x *GetIdentityProviderRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// CreateIdentityProviderRequest is the request message for CreateIdentityProvider
type CreateIdentityProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exact UIDP of the IAM group to nest this identity provider under.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The configuration for an upstream identity provider
	IdentityProvider *IdentityProvider `protobuf:"bytes,2,opt,name=identity_provider,json=identityProvider,proto3" json:"identity_provider,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateIdentityProviderRequest) Reset() {
	*x = CreateIdentityProviderRequest{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIdentityProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIdentityProviderRequest) ProtoMessage() {}

func (x *CreateIdentityProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIdentityProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{4}
}

func (x *CreateIdentityProviderRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateIdentityProviderRequest) GetIdentityProvider() *IdentityProvider {
	if x != nil {
		return x.IdentityProvider
	}
	return nil
}

// UpdateIdentityProviderRequest is the request message for UpdateIdentityProvider.
type UpdateIdentityProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity provider to update.
	IdentityProvider *IdentityProvider `protobuf:"bytes,1,opt,name=identity_provider,json=identityProvider,proto3" json:"identity_provider,omitempty"`
	// The list of fields to update. If not provided, an implied
	// field mask is used equivalent to all fields that are populated
	// (have non-default values). * is supported and interpreted as a full
	// replacement with the given field values.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIdentityProviderRequest) Reset() {
	*x = UpdateIdentityProviderRequest{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIdentityProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIdentityProviderRequest) ProtoMessage() {}

func (x *UpdateIdentityProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIdentityProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIdentityProviderRequest) GetIdentityProvider() *IdentityProvider {
	if x != nil {
		return x.IdentityProvider
	}
	return nil
}

func (x *UpdateIdentityProviderRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteIdentityProviderRequest is the request message for DeleteIdentityProvider.
type DeleteIdentityProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID of the identity provider to delete.
	Uid           string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIdentityProviderRequest) Reset() {
	*x = DeleteIdentityProviderRequest{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityProviderRequest) ProtoMessage() {}

func (x *DeleteIdentityProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteIdentityProviderRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Configuration parameters for performing an OIDC token exchange.
type IdentityProvider_OIDC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Issuer URL (e.g https://accounts.google.com)
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Client ID of the identity provider. This is not considered sensitive.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Client secret of the identity provider. This is a sensitive value
	// and is not returned for list/get calls.
	ClientSecret string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Additional scopes to request for ID tokens from the upstream IdP.
	// Scope openid is always requested as part of the authentication flow.
	AdditionalScopes []string `protobuf:"bytes,4,rep,name=additional_scopes,json=additionalScopes,proto3" json:"additional_scopes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdentityProvider_OIDC) Reset() {
	*x = IdentityProvider_OIDC{}
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProvider_OIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProvider_OIDC) ProtoMessage() {}

func (x *IdentityProvider_OIDC) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProvider_OIDC.ProtoReflect.Descriptor instead.
func (*IdentityProvider_OIDC) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IdentityProvider_OIDC) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IdentityProvider_OIDC) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IdentityProvider_OIDC) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *IdentityProvider_OIDC) GetAdditionalScopes() []string {
	if x != nil {
		return x.AdditionalScopes
	}
	return nil
}

var File_chainguard_platform_iam_v2beta1_identity_providers_proto protoreflect.FileDescriptor

const file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDesc = "" +
	"\n" +
	"8chainguard/platform/iam/v2beta1/identity_providers.proto\x12\x1fchainguard.platform.iam.v2beta1\x1a\x16annotations/auth.proto\x1a\x18annotations/events.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&platform/common/v1/uidp.platform.proto\"\x9e\x05\n" +
	"\x10IdentityProvider\x12\x1c\n" +
	"\x03uid\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x03\x90\xaf\xa8\xd2\x05\x01R\x03uid\x12\x18\n" +
	"\x04name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12&\n" +
	"\vdescription\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\vdescription\x12A\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime\x12'\n" +
	"\fdefault_role\x18\x06 \x01(\tB\x04\xe2A\x01\x02R\vdefaultRole\x12L\n" +
	"\x04oidc\x18\x14 \x01(\v26.chainguard.platform.iam.v2beta1.IdentityProvider.OIDCH\x00R\x04oidc\x1a\xa5\x01\n" +
	"\x04OIDC\x12\x1c\n" +
	"\x06issuer\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06issuer\x12!\n" +
	"\tclient_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\bclientId\x12)\n" +
	"\rclient_secret\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\fclientSecret\x121\n" +
	"\x11additional_scopes\x18\x04 \x03(\tB\x04\xe2A\x01\x01R\x10additionalScopes:t\xeaAq\n" +
	"#iam.chainguard.dev/IdentityProvider\x12%identityProviders/{identity_provider}*\x11identityProviders2\x10identityProviderB\x0f\n" +
	"\rconfiguration\"\xfd\x01\n" +
	"\x1cListIdentityProvidersRequest\x12@\n" +
	"\x04uidp\x18\x01 \x01(\v2&.chainguard.platform.common.UIDPFilterB\x04\xe2A\x01\x01R\x04uidp\x12\x18\n" +
	"\x04name\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\x04name\x12!\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05B\x04\xe2A\x01\x01R\bpageSize\x12#\n" +
	"\n" +
	"page_token\x18\v \x01(\tB\x04\xe2A\x01\x01R\tpageToken\x12\x1f\n" +
	"\border_by\x18\f \x01(\tB\x04\xe2A\x01\x01R\aorderBy\x12\x18\n" +
	"\x04skip\x18\r \x01(\x05B\x04\xe2A\x01\x01R\x04skip\"\xf9\x01\n" +
	"\x1dListIdentityProvidersResponse\x12`\n" +
	"\x12identity_providers\x18\x01 \x03(\v21.chainguard.platform.iam.v2beta1.IdentityProviderR\x11identityProviders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\vtotal_count\x18\x03 \x01(\x03H\x00R\n" +
	"totalCount\x88\x01\x01\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askippedB\x0e\n" +
	"\f_total_count\":\n" +
	"\x1aGetIdentityProviderRequest\x12\x1c\n" +
	"\x03uid\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x03uid\"\xa9\x01\n" +
	"\x1dCreateIdentityProviderRequest\x12\"\n" +
	"\x06parent\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x06parent\x12d\n" +
	"\x11identity_provider\x18\x02 \x01(\v21.chainguard.platform.iam.v2beta1.IdentityProviderB\x04\xe2A\x01\x02R\x10identityProvider\"\xce\x01\n" +
	"\x1dUpdateIdentityProviderRequest\x12j\n" +
	"\x11identity_provider\x18\x01 \x01(\v21.chainguard.platform.iam.v2beta1.IdentityProviderB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x10identityProvider\x12A\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x04\xe2A\x01\x01R\n" +
	"updateMask\"=\n" +
	"\x1dDeleteIdentityProviderRequest\x12\x1c\n" +
	"\x03uid\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x03uid2\x85\n" +
	"\n" +
	"\x18IdentityProvidersService\x12\xcc\x01\n" +
	"\x15ListIdentityProviders\x12=.chainguard.platform.iam.v2beta1.ListIdentityProvidersRequest\x1a>.chainguard.platform.iam.v2beta1.ListIdentityProvidersResponse\"4\x82\xd3\xe4\x93\x02 \x12\x1e/iam/v2beta1/identityProviders\x8a\xaf\xa8\xd2\x05\b\x12\x06\n" +
	"\x02\x97\n" +
	"\x10\x01\x12\xc2\x01\n" +
	"\x13GetIdentityProvider\x12;.chainguard.platform.iam.v2beta1.GetIdentityProviderRequest\x1a1.chainguard.platform.iam.v2beta1.IdentityProvider\";\x82\xd3\xe4\x93\x02)\x12'/iam/v2beta1/identityProviders/{uid=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x97\n" +
	"\x12\xa6\x02\n" +
	"\x16CreateIdentityProvider\x12>.chainguard.platform.iam.v2beta1.CreateIdentityProviderRequest\x1a1.chainguard.platform.iam.v2beta1.IdentityProvider\"\x98\x01\x82\xd3\xe4\x93\x02?:\x11identity_provider\"*/iam/v2beta1/identityProviders/{parent=**}\x8a\xaf\xa8\xd2\x05\b\x12\x06\n" +
	"\x04\x95\n" +
	"\x91\x03\xc2\xf0\x8e\xfc\v?\n" +
	"4dev.chainguard.api.iam.identity_providers.created.v1\x12\x05group\x18\x01\x12\xb5\x02\n" +
	"\x16UpdateIdentityProvider\x12>.chainguard.platform.iam.v2beta1.UpdateIdentityProviderRequest\x1a1.chainguard.platform.iam.v2beta1.IdentityProvider\"\xa7\x01\x82\xd3\xe4\x93\x02N:\x11identity_provider29/iam/v2beta1/identityProviders/{identity_provider.uid=**}\x8a\xaf\xa8\xd2\x05\b\x12\x06\n" +
	"\x04\x96\n" +
	"\x91\x03\xc2\xf0\x8e\xfc\v?\n" +
	"4dev.chainguard.api.iam.identity_providers.updated.v1\x12\x05group\x18\x01\x12\xf3\x01\n" +
	"\x16DeleteIdentityProvider\x12>.chainguard.platform.iam.v2beta1.DeleteIdentityProviderRequest\x1a\x16.google.protobuf.Empty\"\x80\x01\x82\xd3\xe4\x93\x02)*'/iam/v2beta1/identityProviders/{uid=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x98\n" +
	"\xc2\xf0\x8e\xfc\v?\n" +
	"4dev.chainguard.api.iam.identity_providers.deleted.v1\x12\x05group\x18\x01By\n" +
	"#com.chainguard.platform.iam.v2beta1B\x16IdentityProvidersProtoP\x01Z8chainguard.dev/sdk/proto/chainguard/platform/iam/v2beta1b\x06proto3"

var (
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescOnce sync.Once
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescData []byte
)

func file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescGZIP() []byte {
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescOnce.Do(func() {
		file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDesc), len(file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDesc)))
	})
	return file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDescData
}

var file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chainguard_platform_iam_v2beta1_identity_providers_proto_goTypes = []any{
	(*IdentityProvider)(nil),              // 0: chainguard.platform.iam.v2beta1.IdentityProvider
	(*ListIdentityProvidersRequest)(nil),  // 1: chainguard.platform.iam.v2beta1.ListIdentityProvidersRequest
	(*ListIdentityProvidersResponse)(nil), // 2: chainguard.platform.iam.v2beta1.ListIdentityProvidersResponse
	(*GetIdentityProviderRequest)(nil),    // 3: chainguard.platform.iam.v2beta1.GetIdentityProviderRequest
	(*CreateIdentityProviderRequest)(nil), // 4: chainguard.platform.iam.v2beta1.CreateIdentityProviderRequest
	(*UpdateIdentityProviderRequest)(nil), // 5: chainguard.platform.iam.v2beta1.UpdateIdentityProviderRequest
	(*DeleteIdentityProviderRequest)(nil), // 6: chainguard.platform.iam.v2beta1.DeleteIdentityProviderRequest
	(*IdentityProvider_OIDC)(nil),         // 7: chainguard.platform.iam.v2beta1.IdentityProvider.OIDC
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
	(*v1.UIDPFilter)(nil),                 // 9: chainguard.platform.common.UIDPFilter
	(*fieldmaskpb.FieldMask)(nil),         // 10: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                 // 11: google.protobuf.Empty
}
var file_chainguard_platform_iam_v2beta1_identity_providers_proto_depIdxs = []int32{
	8,  // 0: chainguard.platform.iam.v2beta1.IdentityProvider.create_time:type_name -> google.protobuf.Timestamp
	8,  // 1: chainguard.platform.iam.v2beta1.IdentityProvider.update_time:type_name -> google.protobuf.Timestamp
	7,  // 2: chainguard.platform.iam.v2beta1.IdentityProvider.oidc:type_name -> chainguard.platform.iam.v2beta1.IdentityProvider.OIDC
	9,  // 3: chainguard.platform.iam.v2beta1.ListIdentityProvidersRequest.uidp:type_name -> chainguard.platform.common.UIDPFilter
	0,  // 4: chainguard.platform.iam.v2beta1.ListIdentityProvidersResponse.identity_providers:type_name -> chainguard.platform.iam.v2beta1.IdentityProvider
	0,  // 5: chainguard.platform.iam.v2beta1.CreateIdentityProviderRequest.identity_provider:type_name -> chainguard.platform.iam.v2beta1.IdentityProvider
	0,  // 6: chainguard.platform.iam.v2beta1.UpdateIdentityProviderRequest.identity_provider:type_name -> chainguard.platform.iam.v2beta1.IdentityProvider
	10, // 7: chainguard.platform.iam.v2beta1.UpdateIdentityProviderRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 8: chainguard.platform.iam.v2beta1.IdentityProvidersService.ListIdentityProviders:input_type -> chainguard.platform.iam.v2beta1.ListIdentityProvidersRequest
	3,  // 9: chainguard.platform.iam.v2beta1.IdentityProvidersService.GetIdentityProvider:input_type -> chainguard.platform.iam.v2beta1.GetIdentityProviderRequest
	4,  // 10: chainguard.platform.iam.v2beta1.IdentityProvidersService.CreateIdentityProvider:input_type -> chainguard.platform.iam.v2beta1.CreateIdentityProviderRequest
	5,  // 11: chainguard.platform.iam.v2beta1.IdentityProvidersService.UpdateIdentityProvider:input_type -> chainguard.platform.iam.v2beta1.UpdateIdentityProviderRequest
	6,  // 12: chainguard.platform.iam.v2beta1.IdentityProvidersService.DeleteIdentityProvider:input_type -> chainguard.platform.iam.v2beta1.DeleteIdentityProviderRequest
	2,  // 13: chainguard.platform.iam.v2beta1.IdentityProvidersService.ListIdentityProviders:output_type -> chainguard.platform.iam.v2beta1.ListIdentityProvidersResponse
	0,  // 14: chainguard.platform.iam.v2beta1.IdentityProvidersService.GetIdentityProvider:output_type -> chainguard.platform.iam.v2beta1.IdentityProvider
	0,  // 15: chainguard.platform.iam.v2beta1.IdentityProvidersService.CreateIdentityProvider:output_type -> chainguard.platform.iam.v2beta1.IdentityProvider
	0,  // 16: chainguard.platform.iam.v2beta1.IdentityProvidersService.UpdateIdentityProvider:output_type -> chainguard.platform.iam.v2beta1.IdentityProvider
	11, // 17: chainguard.platform.iam.v2beta1.IdentityProvidersService.DeleteIdentityProvider:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chainguard_platform_iam_v2beta1_identity_providers_proto_init() }
func file_chainguard_platform_iam_v2beta1_identity_providers_proto_init() {
	if File_chainguard_platform_iam_v2beta1_identity_providers_proto != nil {
		return
	}
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[0].OneofWrappers = []any{
		(*IdentityProvider_Oidc)(nil),
	}
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDesc), len(file_chainguard_platform_iam_v2beta1_identity_providers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chainguard_platform_iam_v2beta1_identity_providers_proto_goTypes,
		DependencyIndexes: file_chainguard_platform_iam_v2beta1_identity_providers_proto_depIdxs,
		MessageInfos:      file_chainguard_platform_iam_v2beta1_identity_providers_proto_msgTypes,
	}.Build()
	File_chainguard_platform_iam_v2beta1_identity_providers_proto = out.File
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_goTypes = nil
	file_chainguard_platform_iam_v2beta1_identity_providers_proto_depIdxs = nil
}
