// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: chainguard/platform/iam/v2beta1/identities.proto

package v2beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentitiesService_CreateIdentity_FullMethodName = "/chainguard.platform.iam.v2beta1.IdentitiesService/CreateIdentity"
	IdentitiesService_GetIdentity_FullMethodName    = "/chainguard.platform.iam.v2beta1.IdentitiesService/GetIdentity"
	IdentitiesService_DeleteIdentity_FullMethodName = "/chainguard.platform.iam.v2beta1.IdentitiesService/DeleteIdentity"
	IdentitiesService_UpdateIdentity_FullMethodName = "/chainguard.platform.iam.v2beta1.IdentitiesService/UpdateIdentity"
	IdentitiesService_ListIdentities_FullMethodName = "/chainguard.platform.iam.v2beta1.IdentitiesService/ListIdentities"
)

// IdentitiesServiceClient is the client API for IdentitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentitiesService manages IAM identities.
type IdentitiesServiceClient interface {
	// CreateIdentity creates a new identity under a parent group.
	CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*Identity, error)
	// GetIdentity retrieves a single identity by UID.
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*Identity, error)
	// DeleteIdentity deletes an identity by UID.
	DeleteIdentity(ctx context.Context, in *DeleteIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// UpdateIdentity updates the given Identity according to the provided field mask.
	// The fully populated Identity is returned.
	UpdateIdentity(ctx context.Context, in *UpdateIdentityRequest, opts ...grpc.CallOption) (*Identity, error)
	// ListIdentities returns identities based on filter criteria with pagination support.
	ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error)
}

type identitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentitiesServiceClient(cc grpc.ClientConnInterface) IdentitiesServiceClient {
	return &identitiesServiceClient{cc}
}

func (c *identitiesServiceClient) CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, IdentitiesService_CreateIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identitiesServiceClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, IdentitiesService_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identitiesServiceClient) DeleteIdentity(ctx context.Context, in *DeleteIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentitiesService_DeleteIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identitiesServiceClient) UpdateIdentity(ctx context.Context, in *UpdateIdentityRequest, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, IdentitiesService_UpdateIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identitiesServiceClient) ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesResponse)
	err := c.cc.Invoke(ctx, IdentitiesService_ListIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentitiesServiceServer is the server API for IdentitiesService service.
// All implementations must embed UnimplementedIdentitiesServiceServer
// for forward compatibility.
//
// IdentitiesService manages IAM identities.
type IdentitiesServiceServer interface {
	// CreateIdentity creates a new identity under a parent group.
	CreateIdentity(context.Context, *CreateIdentityRequest) (*Identity, error)
	// GetIdentity retrieves a single identity by UID.
	GetIdentity(context.Context, *GetIdentityRequest) (*Identity, error)
	// DeleteIdentity deletes an identity by UID.
	DeleteIdentity(context.Context, *DeleteIdentityRequest) (*emptypb.Empty, error)
	// UpdateIdentity updates the given Identity according to the provided field mask.
	// The fully populated Identity is returned.
	UpdateIdentity(context.Context, *UpdateIdentityRequest) (*Identity, error)
	// ListIdentities returns identities based on filter criteria with pagination support.
	ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error)
	mustEmbedUnimplementedIdentitiesServiceServer()
}

// UnimplementedIdentitiesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentitiesServiceServer struct{}

func (UnimplementedIdentitiesServiceServer) CreateIdentity(context.Context, *CreateIdentityRequest) (*Identity, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIdentity not implemented")
}
func (UnimplementedIdentitiesServiceServer) GetIdentity(context.Context, *GetIdentityRequest) (*Identity, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedIdentitiesServiceServer) DeleteIdentity(context.Context, *DeleteIdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIdentity not implemented")
}
func (UnimplementedIdentitiesServiceServer) UpdateIdentity(context.Context, *UpdateIdentityRequest) (*Identity, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIdentity not implemented")
}
func (UnimplementedIdentitiesServiceServer) ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedIdentitiesServiceServer) mustEmbedUnimplementedIdentitiesServiceServer() {}
func (UnimplementedIdentitiesServiceServer) testEmbeddedByValue()                           {}

// UnsafeIdentitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentitiesServiceServer will
// result in compilation errors.
type UnsafeIdentitiesServiceServer interface {
	mustEmbedUnimplementedIdentitiesServiceServer()
}

func RegisterIdentitiesServiceServer(s grpc.ServiceRegistrar, srv IdentitiesServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentitiesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentitiesService_ServiceDesc, srv)
}

func _IdentitiesService_CreateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServiceServer).CreateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentitiesService_CreateIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServiceServer).CreateIdentity(ctx, req.(*CreateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentitiesService_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServiceServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentitiesService_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServiceServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentitiesService_DeleteIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServiceServer).DeleteIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentitiesService_DeleteIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServiceServer).DeleteIdentity(ctx, req.(*DeleteIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentitiesService_UpdateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServiceServer).UpdateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentitiesService_UpdateIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServiceServer).UpdateIdentity(ctx, req.(*UpdateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentitiesService_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServiceServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentitiesService_ListIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServiceServer).ListIdentities(ctx, req.(*ListIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentitiesService_ServiceDesc is the grpc.ServiceDesc for IdentitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.platform.iam.v2beta1.IdentitiesService",
	HandlerType: (*IdentitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIdentity",
			Handler:    _IdentitiesService_CreateIdentity_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _IdentitiesService_GetIdentity_Handler,
		},
		{
			MethodName: "DeleteIdentity",
			Handler:    _IdentitiesService_DeleteIdentity_Handler,
		},
		{
			MethodName: "UpdateIdentity",
			Handler:    _IdentitiesService_UpdateIdentity_Handler,
		},
		{
			MethodName: "ListIdentities",
			Handler:    _IdentitiesService_ListIdentities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainguard/platform/iam/v2beta1/identities.proto",
}
