// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chainguard/platform/iam/v2beta1/scim_users.proto

package v2beta1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScimUser is a SCIM-provisioned user of an identity provider. Every field is
// server-owned: SCIM users are written by the IdP's SCIM connector, not through
// this API, which is read-only. Name and email attributes are deliberately not
// exposed here (data minimization); use the SCIM protocol endpoint for the full
// user resource.
type ScimUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the SCIM user record (UIDP). Generated by server.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// UID of the identity provider that provisioned this user.
	IdentityProviderUid string `protobuf:"bytes,2,opt,name=identity_provider_uid,json=identityProviderUid,proto3" json:"identity_provider_uid,omitempty"`
	// The SCIM userName attribute, typically an email address.
	UserName string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// The IdP-assigned SCIM externalId, an opaque correlation key. May be empty.
	ExternalId string `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// The SCIM displayName attribute. May be empty.
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The SCIM active flag. When false, the IdP has deprovisioned the user.
	Active bool `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	// UID of the Chainguard IAM identity this SCIM user is linked to. Empty until
	// the user's first login; its presence therefore indicates the user has
	// authenticated at least once.
	IamIdentityUid string `protobuf:"bytes,7,opt,name=iam_identity_uid,json=iamIdentityUid,proto3" json:"iam_identity_uid,omitempty"`
	// When the SCIM user record was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When the SCIM user record was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScimUser) Reset() {
	*x = ScimUser{}
	mi := &file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScimUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScimUser) ProtoMessage() {}

func (x *ScimUser) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScimUser.ProtoReflect.Descriptor instead.
func (*ScimUser) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescGZIP(), []int{0}
}

func (x *ScimUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ScimUser) GetIdentityProviderUid() string {
	if x != nil {
		return x.IdentityProviderUid
	}
	return ""
}

func (x *ScimUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ScimUser) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ScimUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ScimUser) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ScimUser) GetIamIdentityUid() string {
	if x != nil {
		return x.IamIdentityUid
	}
	return ""
}

func (x *ScimUser) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ScimUser) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// ListScimUsersRequest is the request message for ListScimUsers.
type ListScimUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent is the UID of the identity provider whose SCIM users to list. SCIM
	// users are a sub-resource of an identity provider and scope to a single one
	// rather than the group hierarchy, so the parent is required and is the
	// authorization scope (AIP-132 parent).
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Exact match on the SCIM userName (case-insensitive).
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Exact match on the IdP-assigned SCIM externalId.
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// When set, filter by the SCIM active flag.
	Active *bool `protobuf:"varint,4,opt,name=active,proto3,oneof" json:"active,omitempty"`
	// Maximum number of results to return per page.
	// Default: 50, Maximum: 200.
	PageSize int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token from a previous List response for pagination.
	// Opaque token with 3-day expiration.
	PageToken string `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Order results by field. Format: "field [asc|desc]"
	// Default: "uid asc"
	// Note: Changing order_by between pages invalidates the page token.
	OrderBy string `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Number of results to skip before returning.
	// Used for random-access pagination (jumping to arbitrary pages).
	// Can be combined with page_token to skip from cursor position.
	// Must be non-negative.
	Skip          int32 `protobuf:"varint,13,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScimUsersRequest) Reset() {
	*x = ListScimUsersRequest{}
	mi := &file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScimUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScimUsersRequest) ProtoMessage() {}

func (x *ListScimUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScimUsersRequest.ProtoReflect.Descriptor instead.
func (*ListScimUsersRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescGZIP(), []int{1}
}

func (x *ListScimUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListScimUsersRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ListScimUsersRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ListScimUsersRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ListScimUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListScimUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListScimUsersRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListScimUsersRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// ListScimUsersResponse is the response message for ListScimUsers.
type ListScimUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SCIM users matching the filter criteria.
	ScimUsers []*ScimUser `protobuf:"bytes,1,rep,name=scim_users,json=scimUsers,proto3" json:"scim_users,omitempty"`
	// Token for retrieving the next page of results.
	// Empty if no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of results matching the filter.
	// Optional, provided for UI pagination.
	TotalCount *int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	// Number of results that were skipped.
	// Accumulates across paginated requests.
	Skipped       int32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScimUsersResponse) Reset() {
	*x = ListScimUsersResponse{}
	mi := &file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScimUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScimUsersResponse) ProtoMessage() {}

func (x *ListScimUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScimUsersResponse.ProtoReflect.Descriptor instead.
func (*ListScimUsersResponse) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescGZIP(), []int{2}
}

func (x *ListScimUsersResponse) GetScimUsers() []*ScimUser {
	if x != nil {
		return x.ScimUsers
	}
	return nil
}

func (x *ListScimUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListScimUsersResponse) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

func (x *ListScimUsersResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

var File_chainguard_platform_iam_v2beta1_scim_users_proto protoreflect.FileDescriptor

const file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDesc = "" +
	"\n" +
	"0chainguard/platform/iam/v2beta1/scim_users.proto\x12\x1fchainguard.platform.iam.v2beta1\x1a\x16annotations/auth.proto\x1a\x15annotations/mcp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x04\n" +
	"\bScimUser\x12\x16\n" +
	"\x03uid\x18\x01 \x01(\tB\x04\xe2A\x01\x03R\x03uid\x128\n" +
	"\x15identity_provider_uid\x18\x02 \x01(\tB\x04\xe2A\x01\x03R\x13identityProviderUid\x12!\n" +
	"\tuser_name\x18\x03 \x01(\tB\x04\xe2A\x01\x03R\buserName\x12%\n" +
	"\vexternal_id\x18\x04 \x01(\tB\x04\xe2A\x01\x03R\n" +
	"externalId\x12'\n" +
	"\fdisplay_name\x18\x05 \x01(\tB\x04\xe2A\x01\x03R\vdisplayName\x12\x1c\n" +
	"\x06active\x18\x06 \x01(\bB\x04\xe2A\x01\x03R\x06active\x12.\n" +
	"\x10iam_identity_uid\x18\a \x01(\tB\x04\xe2A\x01\x03R\x0eiamIdentityUid\x12A\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime:r\xeaAo\n" +
	"\x1biam.chainguard.dev/ScimUser\x12;identityProviders/{identity_provider}/scimUsers/{scim_user}*\tscimUsers2\bscimUser\"\xb5\x02\n" +
	"\x14ListScimUsersRequest\x12\"\n" +
	"\x06parent\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x06parent\x12!\n" +
	"\tuser_name\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\buserName\x12%\n" +
	"\vexternal_id\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\n" +
	"externalId\x12!\n" +
	"\x06active\x18\x04 \x01(\bB\x04\xe2A\x01\x01H\x00R\x06active\x88\x01\x01\x12!\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05B\x04\xe2A\x01\x01R\bpageSize\x12#\n" +
	"\n" +
	"page_token\x18\v \x01(\tB\x04\xe2A\x01\x01R\tpageToken\x12\x1f\n" +
	"\border_by\x18\f \x01(\tB\x04\xe2A\x01\x01R\aorderBy\x12\x18\n" +
	"\x04skip\x18\r \x01(\x05B\x04\xe2A\x01\x01R\x04skipB\t\n" +
	"\a_active\"\xd9\x01\n" +
	"\x15ListScimUsersResponse\x12H\n" +
	"\n" +
	"scim_users\x18\x01 \x03(\v2).chainguard.platform.iam.v2beta1.ScimUserR\tscimUsers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\vtotal_count\x18\x03 \x01(\x03H\x00R\n" +
	"totalCount\x88\x01\x01\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askippedB\x0e\n" +
	"\f_total_count2\xa4\x03\n" +
	"\x10ScimUsersService\x12\x8f\x03\n" +
	"\rListScimUsers\x125.chainguard.platform.iam.v2beta1.ListScimUsersRequest\x1a6.chainguard.platform.iam.v2beta1.ListScimUsersResponse\"\x8e\x02\x82\xd3\xe4\x93\x026\x124/iam/v2beta1/identityProviders/{parent=**}/scimUsers\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x9a\n" +
	"\x9a\xaf\xa8\xd2\x05\xbf\x01\n" +
	"\xb4\x01List the SCIM-provisioned users of an identity provider, including users provisioned but not yet logged in. Supports filtering by userName, externalId, and active, plus pagination.\x18\x01 \x00(\x010\x00Bq\n" +
	"#com.chainguard.platform.iam.v2beta1B\x0eScimUsersProtoP\x01Z8chainguard.dev/sdk/proto/chainguard/platform/iam/v2beta1b\x06proto3"

var (
	file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescOnce sync.Once
	file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescData []byte
)

func file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescGZIP() []byte {
	file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescOnce.Do(func() {
		file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDesc), len(file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDesc)))
	})
	return file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDescData
}

var file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chainguard_platform_iam_v2beta1_scim_users_proto_goTypes = []any{
	(*ScimUser)(nil),              // 0: chainguard.platform.iam.v2beta1.ScimUser
	(*ListScimUsersRequest)(nil),  // 1: chainguard.platform.iam.v2beta1.ListScimUsersRequest
	(*ListScimUsersResponse)(nil), // 2: chainguard.platform.iam.v2beta1.ListScimUsersResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_chainguard_platform_iam_v2beta1_scim_users_proto_depIdxs = []int32{
	3, // 0: chainguard.platform.iam.v2beta1.ScimUser.create_time:type_name -> google.protobuf.Timestamp
	3, // 1: chainguard.platform.iam.v2beta1.ScimUser.update_time:type_name -> google.protobuf.Timestamp
	0, // 2: chainguard.platform.iam.v2beta1.ListScimUsersResponse.scim_users:type_name -> chainguard.platform.iam.v2beta1.ScimUser
	1, // 3: chainguard.platform.iam.v2beta1.ScimUsersService.ListScimUsers:input_type -> chainguard.platform.iam.v2beta1.ListScimUsersRequest
	2, // 4: chainguard.platform.iam.v2beta1.ScimUsersService.ListScimUsers:output_type -> chainguard.platform.iam.v2beta1.ListScimUsersResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chainguard_platform_iam_v2beta1_scim_users_proto_init() }
func file_chainguard_platform_iam_v2beta1_scim_users_proto_init() {
	if File_chainguard_platform_iam_v2beta1_scim_users_proto != nil {
		return
	}
	file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[1].OneofWrappers = []any{}
	file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDesc), len(file_chainguard_platform_iam_v2beta1_scim_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chainguard_platform_iam_v2beta1_scim_users_proto_goTypes,
		DependencyIndexes: file_chainguard_platform_iam_v2beta1_scim_users_proto_depIdxs,
		MessageInfos:      file_chainguard_platform_iam_v2beta1_scim_users_proto_msgTypes,
	}.Build()
	File_chainguard_platform_iam_v2beta1_scim_users_proto = out.File
	file_chainguard_platform_iam_v2beta1_scim_users_proto_goTypes = nil
	file_chainguard_platform_iam_v2beta1_scim_users_proto_depIdxs = nil
}
