// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: chainguard/platform/guardener/v1alpha1/github_associations.proto

package v1alpha1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_GitHubAssociations_BeginGitHubOAuth_0(ctx context.Context, marshaler runtime.Marshaler, client GitHubAssociationsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BeginGitHubOAuthRequest
	var metadata runtime.ServerMetadata

	msg, err := client.BeginGitHubOAuth(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GitHubAssociations_BeginGitHubOAuth_0(ctx context.Context, marshaler runtime.Marshaler, server GitHubAssociationsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BeginGitHubOAuthRequest
	var metadata runtime.ServerMetadata

	msg, err := server.BeginGitHubOAuth(ctx, &protoReq)
	return msg, metadata, err

}

func request_GitHubAssociations_LinkGitHubOrganization_0(ctx context.Context, marshaler runtime.Marshaler, client GitHubAssociationsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq LinkGitHubOrganizationRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["group"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "group")
	}

	protoReq.Group, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "group", err)
	}

	msg, err := client.LinkGitHubOrganization(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GitHubAssociations_LinkGitHubOrganization_0(ctx context.Context, marshaler runtime.Marshaler, server GitHubAssociationsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq LinkGitHubOrganizationRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["group"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "group")
	}

	protoReq.Group, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "group", err)
	}

	msg, err := server.LinkGitHubOrganization(ctx, &protoReq)
	return msg, metadata, err

}

func request_GitHubAssociations_UnlinkGitHubOrganization_0(ctx context.Context, marshaler runtime.Marshaler, client GitHubAssociationsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UnlinkGitHubOrganizationRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.UnlinkGitHubOrganization(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GitHubAssociations_UnlinkGitHubOrganization_0(ctx context.Context, marshaler runtime.Marshaler, server GitHubAssociationsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UnlinkGitHubOrganizationRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.UnlinkGitHubOrganization(ctx, &protoReq)
	return msg, metadata, err

}

func request_GitHubAssociations_UnlinkGitHubOrganization_1(ctx context.Context, marshaler runtime.Marshaler, client GitHubAssociationsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UnlinkGitHubOrganizationRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["group"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "group")
	}

	if protoReq.Credentials == nil {
		protoReq.Credentials = &UnlinkGitHubOrganizationRequest_Group{}
	} else if _, ok := protoReq.Credentials.(*UnlinkGitHubOrganizationRequest_Group); !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "expect type: *UnlinkGitHubOrganizationRequest_Group, but: %t\n", protoReq.Credentials)
	}
	protoReq.Credentials.(*UnlinkGitHubOrganizationRequest_Group).Group, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "group", err)
	}

	msg, err := client.UnlinkGitHubOrganization(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GitHubAssociations_UnlinkGitHubOrganization_1(ctx context.Context, marshaler runtime.Marshaler, server GitHubAssociationsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UnlinkGitHubOrganizationRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["group"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "group")
	}

	if protoReq.Credentials == nil {
		protoReq.Credentials = &UnlinkGitHubOrganizationRequest_Group{}
	} else if _, ok := protoReq.Credentials.(*UnlinkGitHubOrganizationRequest_Group); !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "expect type: *UnlinkGitHubOrganizationRequest_Group, but: %t\n", protoReq.Credentials)
	}
	protoReq.Credentials.(*UnlinkGitHubOrganizationRequest_Group).Group, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "group", err)
	}

	msg, err := server.UnlinkGitHubOrganization(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterGitHubAssociationsHandlerServer registers the http handlers for service GitHubAssociations to "mux".
// UnaryRPC     :call GitHubAssociationsServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterGitHubAssociationsHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterGitHubAssociationsHandlerServer(ctx context.Context, mux *runtime.ServeMux, server GitHubAssociationsServer) error {

	mux.Handle("GET", pattern_GitHubAssociations_BeginGitHubOAuth_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/BeginGitHubOAuth", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations:begin"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GitHubAssociations_BeginGitHubOAuth_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_BeginGitHubOAuth_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_GitHubAssociations_LinkGitHubOrganization_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/LinkGitHubOrganization", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations/{group=**}:link"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GitHubAssociations_LinkGitHubOrganization_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_LinkGitHubOrganization_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_GitHubAssociations_UnlinkGitHubOrganization_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/UnlinkGitHubOrganization", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations:unlink"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GitHubAssociations_UnlinkGitHubOrganization_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_UnlinkGitHubOrganization_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_GitHubAssociations_UnlinkGitHubOrganization_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/UnlinkGitHubOrganization", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations/{group=**}:unlink"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GitHubAssociations_UnlinkGitHubOrganization_1(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_UnlinkGitHubOrganization_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterGitHubAssociationsHandlerFromEndpoint is same as RegisterGitHubAssociationsHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterGitHubAssociationsHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterGitHubAssociationsHandler(ctx, mux, conn)
}

// RegisterGitHubAssociationsHandler registers the http handlers for service GitHubAssociations to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterGitHubAssociationsHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGitHubAssociationsHandlerClient(ctx, mux, NewGitHubAssociationsClient(conn))
}

// RegisterGitHubAssociationsHandlerClient registers the http handlers for service GitHubAssociations
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "GitHubAssociationsClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "GitHubAssociationsClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "GitHubAssociationsClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterGitHubAssociationsHandlerClient(ctx context.Context, mux *runtime.ServeMux, client GitHubAssociationsClient) error {

	mux.Handle("GET", pattern_GitHubAssociations_BeginGitHubOAuth_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/BeginGitHubOAuth", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations:begin"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GitHubAssociations_BeginGitHubOAuth_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_BeginGitHubOAuth_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_GitHubAssociations_LinkGitHubOrganization_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/LinkGitHubOrganization", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations/{group=**}:link"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GitHubAssociations_LinkGitHubOrganization_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_LinkGitHubOrganization_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_GitHubAssociations_UnlinkGitHubOrganization_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/UnlinkGitHubOrganization", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations:unlink"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GitHubAssociations_UnlinkGitHubOrganization_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_UnlinkGitHubOrganization_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_GitHubAssociations_UnlinkGitHubOrganization_1, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/chainguard.platform.guardener.v1alpha1.GitHubAssociations/UnlinkGitHubOrganization", runtime.WithHTTPPathPattern("/guardener/v1alpha1/githubAssociations/{group=**}:unlink"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GitHubAssociations_UnlinkGitHubOrganization_1(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GitHubAssociations_UnlinkGitHubOrganization_1(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_GitHubAssociations_BeginGitHubOAuth_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"guardener", "v1alpha1", "githubAssociations"}, "begin"))

	pattern_GitHubAssociations_LinkGitHubOrganization_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 3, 0, 4, 1, 5, 3}, []string{"guardener", "v1alpha1", "githubAssociations", "group"}, "link"))

	pattern_GitHubAssociations_UnlinkGitHubOrganization_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"guardener", "v1alpha1", "githubAssociations"}, "unlink"))

	pattern_GitHubAssociations_UnlinkGitHubOrganization_1 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 3, 0, 4, 1, 5, 3}, []string{"guardener", "v1alpha1", "githubAssociations", "group"}, "unlink"))
)

var (
	forward_GitHubAssociations_BeginGitHubOAuth_0 = runtime.ForwardResponseMessage

	forward_GitHubAssociations_LinkGitHubOrganization_0 = runtime.ForwardResponseMessage

	forward_GitHubAssociations_UnlinkGitHubOrganization_0 = runtime.ForwardResponseMessage

	forward_GitHubAssociations_UnlinkGitHubOrganization_1 = runtime.ForwardResponseMessage
)
