// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: chainguard/platform/guardener/v1alpha1/guardener.proto

package v1alpha1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trigger identifies what initiated a migration run.
type Trigger int32

const (
	Trigger_TRIGGER_UNSPECIFIED Trigger = 0
	// A user enqueued the migration via MigrateRepository.
	Trigger_TRIGGER_USER Trigger = 1
	// The system (cron migrator) enqueued the migration.
	Trigger_TRIGGER_SYSTEM Trigger = 2
)

// Enum value maps for Trigger.
var (
	Trigger_name = map[int32]string{
		0: "TRIGGER_UNSPECIFIED",
		1: "TRIGGER_USER",
		2: "TRIGGER_SYSTEM",
	}
	Trigger_value = map[string]int32{
		"TRIGGER_UNSPECIFIED": 0,
		"TRIGGER_USER":        1,
		"TRIGGER_SYSTEM":      2,
	}
)

func (x Trigger) Enum() *Trigger {
	p := new(Trigger)
	*p = x
	return p
}

func (x Trigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Trigger) Descriptor() protoreflect.EnumDescriptor {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes[0].Descriptor()
}

func (Trigger) Type() protoreflect.EnumType {
	return &file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes[0]
}

func (x Trigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Trigger.Descriptor instead.
func (Trigger) EnumDescriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{0}
}

// MigrationFeature identifies the repository migration worker.
type MigrationFeature int32

const (
	// Legacy operations did not identify their Actions worker explicitly.
	MigrationFeature_MIGRATION_FEATURE_UNSPECIFIED MigrationFeature = 0
	// GitHub Actions workflow migration.
	MigrationFeature_MIGRATION_FEATURE_ACTIONS MigrationFeature = 1
	// Container image reference migration.
	MigrationFeature_MIGRATION_FEATURE_IMAGES MigrationFeature = 2
)

// Enum value maps for MigrationFeature.
var (
	MigrationFeature_name = map[int32]string{
		0: "MIGRATION_FEATURE_UNSPECIFIED",
		1: "MIGRATION_FEATURE_ACTIONS",
		2: "MIGRATION_FEATURE_IMAGES",
	}
	MigrationFeature_value = map[string]int32{
		"MIGRATION_FEATURE_UNSPECIFIED": 0,
		"MIGRATION_FEATURE_ACTIONS":     1,
		"MIGRATION_FEATURE_IMAGES":      2,
	}
)

func (x MigrationFeature) Enum() *MigrationFeature {
	p := new(MigrationFeature)
	*p = x
	return p
}

func (x MigrationFeature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationFeature) Descriptor() protoreflect.EnumDescriptor {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes[1].Descriptor()
}

func (MigrationFeature) Type() protoreflect.EnumType {
	return &file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes[1]
}

func (x MigrationFeature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationFeature.Descriptor instead.
func (MigrationFeature) EnumDescriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{1}
}

// RepoVisibilityScope controls which repositories guardener responds to for the
// group.
type Entitlement_RepoVisibilityScope int32

const (
	// Unspecified is the default when no entitlement is configured; treated as
	// PUBLIC.
	Entitlement_REPO_VISIBILITY_SCOPE_UNSPECIFIED Entitlement_RepoVisibilityScope = 0
	// Guardener responds only to public repositories.
	// buf:lint:ignore ENUM_VALUE_PREFIX
	Entitlement_PUBLIC Entitlement_RepoVisibilityScope = 1
	// Guardener responds to all repositories (public and private).
	// buf:lint:ignore ENUM_VALUE_PREFIX
	Entitlement_ALL Entitlement_RepoVisibilityScope = 2
)

// Enum value maps for Entitlement_RepoVisibilityScope.
var (
	Entitlement_RepoVisibilityScope_name = map[int32]string{
		0: "REPO_VISIBILITY_SCOPE_UNSPECIFIED",
		1: "PUBLIC",
		2: "ALL",
	}
	Entitlement_RepoVisibilityScope_value = map[string]int32{
		"REPO_VISIBILITY_SCOPE_UNSPECIFIED": 0,
		"PUBLIC":                            1,
		"ALL":                               2,
	}
)

func (x Entitlement_RepoVisibilityScope) Enum() *Entitlement_RepoVisibilityScope {
	p := new(Entitlement_RepoVisibilityScope)
	*p = x
	return p
}

func (x Entitlement_RepoVisibilityScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entitlement_RepoVisibilityScope) Descriptor() protoreflect.EnumDescriptor {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes[2].Descriptor()
}

func (Entitlement_RepoVisibilityScope) Type() protoreflect.EnumType {
	return &file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes[2]
}

func (x Entitlement_RepoVisibilityScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entitlement_RepoVisibilityScope.Descriptor instead.
func (Entitlement_RepoVisibilityScope) EnumDescriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{0, 0}
}

// Entitlement holds the support-configurable settings for a group.
type Entitlement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group is the Chainguard group UIDP the entitlement applies to.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// repo_visibility_scope controls which repositories guardener responds to for
	// the group.
	RepoVisibilityScope Entitlement_RepoVisibilityScope `protobuf:"varint,2,opt,name=repo_visibility_scope,json=repoVisibilityScope,proto3,enum=chainguard.platform.guardener.v1alpha1.Entitlement_RepoVisibilityScope" json:"repo_visibility_scope,omitempty"`
	// create_time is when the entitlement was first configured.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// update_time is when the entitlement was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entitlement) Reset() {
	*x = Entitlement{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entitlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entitlement) ProtoMessage() {}

func (x *Entitlement) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entitlement.ProtoReflect.Descriptor instead.
func (*Entitlement) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{0}
}

func (x *Entitlement) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Entitlement) GetRepoVisibilityScope() Entitlement_RepoVisibilityScope {
	if x != nil {
		return x.RepoVisibilityScope
	}
	return Entitlement_REPO_VISIBILITY_SCOPE_UNSPECIFIED
}

func (x *Entitlement) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Entitlement) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GetEntitlementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group is the Chainguard group UIDP whose entitlement to fetch.
	Group         string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitlementRequest) Reset() {
	*x = GetEntitlementRequest{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitlementRequest) ProtoMessage() {}

func (x *GetEntitlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitlementRequest.ProtoReflect.Descriptor instead.
func (*GetEntitlementRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{1}
}

func (x *GetEntitlementRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type UpdateEntitlementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group is the Chainguard group UIDP whose entitlement to create or update.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// repo_visibility_scope is the repo visibility scope to set for the group.
	RepoVisibilityScope Entitlement_RepoVisibilityScope `protobuf:"varint,2,opt,name=repo_visibility_scope,json=repoVisibilityScope,proto3,enum=chainguard.platform.guardener.v1alpha1.Entitlement_RepoVisibilityScope" json:"repo_visibility_scope,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateEntitlementRequest) Reset() {
	*x = UpdateEntitlementRequest{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntitlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntitlementRequest) ProtoMessage() {}

func (x *UpdateEntitlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntitlementRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntitlementRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEntitlementRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *UpdateEntitlementRequest) GetRepoVisibilityScope() Entitlement_RepoVisibilityScope {
	if x != nil {
		return x.RepoVisibilityScope
	}
	return Entitlement_REPO_VISIBILITY_SCOPE_UNSPECIFIED
}

type MigrateRepositoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UIDP of the caller's group (org). Must own the repository's installation.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Full URL of the repository to migrate, e.g.
	// "https://github.com/owner/repo". Only github.com is supported today; the
	// field is a URL so other forges (GitHub Enterprise, GitLab) can be supported
	// without a request change.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Run registered migrations enabled by the repository's configuration.
	// Permissions and deployment availability are reported per feature.
	// False preserves legacy Actions-only behavior.
	ConfiguredMigrations bool `protobuf:"varint,3,opt,name=configured_migrations,json=configuredMigrations,proto3" json:"configured_migrations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MigrateRepositoryRequest) Reset() {
	*x = MigrateRepositoryRequest{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRepositoryRequest) ProtoMessage() {}

func (x *MigrateRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRepositoryRequest.ProtoReflect.Descriptor instead.
func (*MigrateRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{3}
}

func (x *MigrateRepositoryRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *MigrateRepositoryRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MigrateRepositoryRequest) GetConfiguredMigrations() bool {
	if x != nil {
		return x.ConfiguredMigrations
	}
	return false
}

// MigrationFeatureResult describes one feature in a configured migration.
type MigrationFeatureResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The feature whose effective configuration controls this migration.
	Feature MigrationFeature `protobuf:"varint,1,opt,name=feature,proto3,enum=chainguard.platform.guardener.v1alpha1.MigrationFeature" json:"feature,omitempty"`
	// The feature's child operation, namespaced under the same group.
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// False means queued or running. True does not imply success: check error.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// The PR created or updated, when there are changes.
	PullRequestUrl string `protobuf:"bytes,4,opt,name=pull_request_url,json=pullRequestUrl,proto3" json:"pull_request_url,omitempty"`
	// True when the feature completed successfully without edits.
	NoOp bool `protobuf:"varint,5,opt,name=no_op,json=noOp,proto3" json:"no_op,omitempty"`
	// True when repository configuration or the deployment disabled migration.
	Disabled bool `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// A terminal failure for this feature. Other features may have succeeded.
	Error         *status.Status `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationFeatureResult) Reset() {
	*x = MigrationFeatureResult{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationFeatureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationFeatureResult) ProtoMessage() {}

func (x *MigrationFeatureResult) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationFeatureResult.ProtoReflect.Descriptor instead.
func (*MigrationFeatureResult) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{4}
}

func (x *MigrationFeatureResult) GetFeature() MigrationFeature {
	if x != nil {
		return x.Feature
	}
	return MigrationFeature_MIGRATION_FEATURE_UNSPECIFIED
}

func (x *MigrationFeatureResult) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MigrationFeatureResult) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *MigrationFeatureResult) GetPullRequestUrl() string {
	if x != nil {
		return x.PullRequestUrl
	}
	return ""
}

func (x *MigrationFeatureResult) GetNoOp() bool {
	if x != nil {
		return x.NoOp
	}
	return false
}

func (x *MigrationFeatureResult) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *MigrationFeatureResult) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetMigrationOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UIDP of the owning group; the IAM scope. Must match the UIDP embedded in
	// the operation name.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// The operation name, as returned by MigrateRepository
	// (operations/migrate/{uidp}/{uuid}).
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationOperationRequest) Reset() {
	*x = GetMigrationOperationRequest{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationOperationRequest) ProtoMessage() {}

func (x *GetMigrationOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationOperationRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationOperationRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{5}
}

func (x *GetMigrationOperationRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetMigrationOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// MigrateOperationMetadata is carried in Operation.metadata while a migration
// is running and when it is done.
type MigrateOperationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full URL of the repository being migrated, e.g.
	// "https://github.com/owner/repo".
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// The workqueue key for the repository's migration.
	RepoKey string `protobuf:"bytes,2,opt,name=repo_key,json=repoKey,proto3" json:"repo_key,omitempty"`
	// When the operation was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// What triggered the run (user vs system).
	Trigger Trigger `protobuf:"varint,4,opt,name=trigger,proto3,enum=chainguard.platform.guardener.v1alpha1.Trigger" json:"trigger,omitempty"`
	// The identity that triggered the run: the caller's subject for user-
	// triggered runs, or the reconciler/cron identity for system-triggered runs.
	Actor string `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	// The worker awaited by a leaf operation; unset for legacy Actions.
	Feature MigrationFeature `protobuf:"varint,6,opt,name=feature,proto3,enum=chainguard.platform.guardener.v1alpha1.MigrationFeature" json:"feature,omitempty"`
	// True when this operation tracks configuration-driven feature migrations.
	ConfiguredMigrations bool `protobuf:"varint,7,opt,name=configured_migrations,json=configuredMigrations,proto3" json:"configured_migrations,omitempty"`
	// Progress of each feature, including any already-completed PRs or failures.
	Results       []*MigrationFeatureResult `protobuf:"bytes,8,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateOperationMetadata) Reset() {
	*x = MigrateOperationMetadata{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateOperationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateOperationMetadata) ProtoMessage() {}

func (x *MigrateOperationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateOperationMetadata.ProtoReflect.Descriptor instead.
func (*MigrateOperationMetadata) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{6}
}

func (x *MigrateOperationMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MigrateOperationMetadata) GetRepoKey() string {
	if x != nil {
		return x.RepoKey
	}
	return ""
}

func (x *MigrateOperationMetadata) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *MigrateOperationMetadata) GetTrigger() Trigger {
	if x != nil {
		return x.Trigger
	}
	return Trigger_TRIGGER_UNSPECIFIED
}

func (x *MigrateOperationMetadata) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *MigrateOperationMetadata) GetFeature() MigrationFeature {
	if x != nil {
		return x.Feature
	}
	return MigrationFeature_MIGRATION_FEATURE_UNSPECIFIED
}

func (x *MigrateOperationMetadata) GetConfiguredMigrations() bool {
	if x != nil {
		return x.ConfiguredMigrations
	}
	return false
}

func (x *MigrateOperationMetadata) GetResults() []*MigrationFeatureResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// MigrateOperationResponse is carried in Operation.response when a migration
// completes. Leaf failures use Operation.error. Configured requests instead
// carry independent feature failures in results so successful PRs remain
// visible.
type MigrateOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The migration pull request opened or updated by the run. Empty when the
	// run was a no-op (nothing to migrate).
	PullRequestUrl string `protobuf:"bytes,1,opt,name=pull_request_url,json=pullRequestUrl,proto3" json:"pull_request_url,omitempty"`
	// True when the run completed but produced no pull request (opted out, no
	// edits, or no net changes).
	NoOp bool `protobuf:"varint,2,opt,name=no_op,json=noOp,proto3" json:"no_op,omitempty"`
	// True when repository configuration or the deployment disabled migration.
	Disabled bool `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Results for a configured request. The parent completes after all children
	// terminate; check each error before treating the request as successful.
	Results       []*MigrationFeatureResult `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateOperationResponse) Reset() {
	*x = MigrateOperationResponse{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateOperationResponse) ProtoMessage() {}

func (x *MigrateOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateOperationResponse.ProtoReflect.Descriptor instead.
func (*MigrateOperationResponse) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{7}
}

func (x *MigrateOperationResponse) GetPullRequestUrl() string {
	if x != nil {
		return x.PullRequestUrl
	}
	return ""
}

func (x *MigrateOperationResponse) GetNoOp() bool {
	if x != nil {
		return x.NoOp
	}
	return false
}

func (x *MigrateOperationResponse) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *MigrateOperationResponse) GetResults() []*MigrationFeatureResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListScansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UIDP of the caller's group; the IAM scope. Scans are stored per group, so
	// this scopes the listing to the group's own scans.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Optional: filters the listing to one repository, as its host-prefixed
	// path, e.g. "github.com/owner/repo". Carried as a query parameter over
	// HTTP: a group UIDP and a repository path are both hierarchical, and only
	// one of them can be a multi-segment URL path variable. The field is a
	// path, not a fixed segment count, so forges with nested namespaces (e.g.
	// GitLab subgroups) can be supported without a request change; only
	// github.com repositories are scanned today.
	Repo          string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScansRequest) Reset() {
	*x = ListScansRequest{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScansRequest) ProtoMessage() {}

func (x *ListScansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScansRequest.ProtoReflect.Descriptor instead.
func (*ListScansRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{8}
}

func (x *ListScansRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ListScansRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ListScansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching scan summaries, newest first (one per repository: its most
	// recent scan).
	Scans         []*ScanSummary `protobuf:"bytes,1,rep,name=scans,proto3" json:"scans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScansResponse) Reset() {
	*x = ListScansResponse{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScansResponse) ProtoMessage() {}

func (x *ListScansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScansResponse.ProtoReflect.Descriptor instead.
func (*ListScansResponse) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{9}
}

func (x *ListScansResponse) GetScans() []*ScanSummary {
	if x != nil {
		return x.Scans
	}
	return nil
}

// ScanSummary identifies one dependency scan without its artifact payload.
type ScanSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque id of the scan, unique within the group; resolve it to the full
	// scan with GetScan. Ids are stable for the lifetime of the scan but carry
	// no format guarantee — treat them as opaque tokens.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The repository that was scanned, as its host-prefixed path, e.g.
	// "github.com/owner/repo".
	Repo string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	// The commit that was scanned (the repository's default-branch HEAD at scan
	// time).
	CommitSha string `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	// When the scan ran.
	ScanTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scan_time,json=scanTime,proto3" json:"scan_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanSummary) Reset() {
	*x = ScanSummary{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanSummary) ProtoMessage() {}

func (x *ScanSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanSummary.ProtoReflect.Descriptor instead.
func (*ScanSummary) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{10}
}

func (x *ScanSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanSummary) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ScanSummary) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *ScanSummary) GetScanTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScanTime
	}
	return nil
}

type GetScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UIDP of the caller's group; the IAM scope. Scan ids only resolve within
	// the group that owns them.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// The scan id, from a ListScans summary.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanRequest) Reset() {
	*x = GetScanRequest{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanRequest) ProtoMessage() {}

func (x *GetScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanRequest.ProtoReflect.Descriptor instead.
func (*GetScanRequest) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{11}
}

func (x *GetScanRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetScanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Scan is one dependency scan of a repository at a commit: the declared
// artifacts and the relationships between them.
type Scan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque id of the scan (see ScanSummary.id).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The repository that was scanned, as its host-prefixed path, e.g.
	// "github.com/owner/repo".
	Repo string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	// The commit that was scanned (the repository's default-branch HEAD at scan
	// time).
	CommitSha string `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	// When the scan ran.
	ScanTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scan_time,json=scanTime,proto3" json:"scan_time,omitempty"`
	// The artifacts the repository declares.
	Artifacts []*ScanArtifact `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// The relationships between artifacts.
	Relationships []*ScanRelationship `protobuf:"bytes,6,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{12}
}

func (x *Scan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scan) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Scan) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Scan) GetScanTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScanTime
	}
	return nil
}

func (x *Scan) GetArtifacts() []*ScanArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Scan) GetRelationships() []*ScanRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

// ScanArtifact is one declared artifact found by a scan.
type ScanArtifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier of the artifact within this scan; the join key for
	// ScanRelationship endpoints.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Package URL (https://github.com/package-url/purl-spec) of the artifact.
	Purl string `protobuf:"bytes,2,opt,name=purl,proto3" json:"purl,omitempty"`
	// Repository-relative paths of the files that declared the artifact (e.g.
	// "go.mod", "service/Dockerfile").
	Paths         []string `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanArtifact) Reset() {
	*x = ScanArtifact{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanArtifact) ProtoMessage() {}

func (x *ScanArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanArtifact.ProtoReflect.Descriptor instead.
func (*ScanArtifact) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{13}
}

func (x *ScanArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanArtifact) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *ScanArtifact) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// ScanRelationship is one relationship between two artifacts of a scan.
type ScanRelationship struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ScanArtifact.id of the relationship's source.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// ScanArtifact.id of the relationship's target.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// The relationship type (e.g. "dependency-of").
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRelationship) Reset() {
	*x = ScanRelationship{}
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRelationship) ProtoMessage() {}

func (x *ScanRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRelationship.ProtoReflect.Descriptor instead.
func (*ScanRelationship) Descriptor() ([]byte, []int) {
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP(), []int{14}
}

func (x *ScanRelationship) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ScanRelationship) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ScanRelationship) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_chainguard_platform_guardener_v1alpha1_guardener_proto protoreflect.FileDescriptor

const file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDesc = "" +
	"\n" +
	"6chainguard/platform/guardener/v1alpha1/guardener.proto\x12&chainguard.platform.guardener.v1alpha1\x1a\x16annotations/auth.proto\x1a\x15annotations/mcp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a#google/longrunning/operations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\"\x85\x03\n" +
	"\vEntitlement\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\x12{\n" +
	"\x15repo_visibility_scope\x18\x02 \x01(\x0e2G.chainguard.platform.guardener.v1alpha1.Entitlement.RepoVisibilityScopeR\x13repoVisibilityScope\x12A\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime\"Q\n" +
	"\x13RepoVisibilityScope\x12%\n" +
	"!REPO_VISIBILITY_SCOPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\a\n" +
	"\x03ALL\x10\x02\"9\n" +
	"\x15GetEntitlementRequest\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\"\xb9\x01\n" +
	"\x18UpdateEntitlementRequest\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\x12{\n" +
	"\x15repo_visibility_scope\x18\x02 \x01(\x0e2G.chainguard.platform.guardener.v1alpha1.Entitlement.RepoVisibilityScopeR\x13repoVisibilityScope\"\x8f\x01\n" +
	"\x18MigrateRepositoryRequest\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\x12\x16\n" +
	"\x03url\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x03url\x129\n" +
	"\x15configured_migrations\x18\x03 \x01(\bB\x04\xe2A\x01\x01R\x14configuredMigrations\"\xcd\x02\n" +
	"\x16MigrationFeatureResult\x12X\n" +
	"\afeature\x18\x01 \x01(\x0e28.chainguard.platform.guardener.v1alpha1.MigrationFeatureB\x04\xe2A\x01\x03R\afeature\x12\"\n" +
	"\toperation\x18\x02 \x01(\tB\x04\xe2A\x01\x03R\toperation\x12\x18\n" +
	"\x04done\x18\x03 \x01(\bB\x04\xe2A\x01\x03R\x04done\x12.\n" +
	"\x10pull_request_url\x18\x04 \x01(\tB\x04\xe2A\x01\x03R\x0epullRequestUrl\x12\x19\n" +
	"\x05no_op\x18\x05 \x01(\bB\x04\xe2A\x01\x03R\x04noOp\x12 \n" +
	"\bdisabled\x18\x06 \x01(\bB\x04\xe2A\x01\x03R\bdisabled\x12.\n" +
	"\x05error\x18\a \x01(\v2\x12.google.rpc.StatusB\x04\xe2A\x01\x03R\x05error\"Z\n" +
	"\x1cGetMigrationOperationRequest\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\x12\x18\n" +
	"\x04name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\xda\x03\n" +
	"\x18MigrateOperationMetadata\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\brepo_key\x18\x02 \x01(\tR\arepoKey\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12I\n" +
	"\atrigger\x18\x04 \x01(\x0e2/.chainguard.platform.guardener.v1alpha1.TriggerR\atrigger\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\x12X\n" +
	"\afeature\x18\x06 \x01(\x0e28.chainguard.platform.guardener.v1alpha1.MigrationFeatureB\x04\xe2A\x01\x03R\afeature\x129\n" +
	"\x15configured_migrations\x18\a \x01(\bB\x04\xe2A\x01\x03R\x14configuredMigrations\x12^\n" +
	"\aresults\x18\b \x03(\v2>.chainguard.platform.guardener.v1alpha1.MigrationFeatureResultB\x04\xe2A\x01\x03R\aresults\"\xdb\x01\n" +
	"\x18MigrateOperationResponse\x12(\n" +
	"\x10pull_request_url\x18\x01 \x01(\tR\x0epullRequestUrl\x12\x13\n" +
	"\x05no_op\x18\x02 \x01(\bR\x04noOp\x12 \n" +
	"\bdisabled\x18\x03 \x01(\bB\x04\xe2A\x01\x03R\bdisabled\x12^\n" +
	"\aresults\x18\x04 \x03(\v2>.chainguard.platform.guardener.v1alpha1.MigrationFeatureResultB\x04\xe2A\x01\x03R\aresults\"H\n" +
	"\x10ListScansRequest\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"^\n" +
	"\x11ListScansResponse\x12I\n" +
	"\x05scans\x18\x01 \x03(\v23.chainguard.platform.guardener.v1alpha1.ScanSummaryR\x05scans\"\x89\x01\n" +
	"\vScanSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x127\n" +
	"\tscan_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bscanTime\"H\n" +
	"\x0eGetScanRequest\x12 \n" +
	"\x05group\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02\x90\xaf\xa8\xd2\x05\x01R\x05group\x12\x14\n" +
	"\x02id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x02id\"\xb6\x02\n" +
	"\x04Scan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x127\n" +
	"\tscan_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bscanTime\x12R\n" +
	"\tartifacts\x18\x05 \x03(\v24.chainguard.platform.guardener.v1alpha1.ScanArtifactR\tartifacts\x12^\n" +
	"\rrelationships\x18\x06 \x03(\v28.chainguard.platform.guardener.v1alpha1.ScanRelationshipR\rrelationships\"H\n" +
	"\fScanArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04purl\x18\x02 \x01(\tR\x04purl\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\"J\n" +
	"\x10ScanRelationship\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type*H\n" +
	"\aTrigger\x12\x17\n" +
	"\x13TRIGGER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTRIGGER_USER\x10\x01\x12\x12\n" +
	"\x0eTRIGGER_SYSTEM\x10\x02*r\n" +
	"\x10MigrationFeature\x12!\n" +
	"\x1dMIGRATION_FEATURE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MIGRATION_FEATURE_ACTIONS\x10\x01\x12\x1c\n" +
	"\x18MIGRATION_FEATURE_IMAGES\x10\x022\xf4\x0e\n" +
	"\tGuardener\x12\xc5\x01\n" +
	"\x0eGetEntitlement\x12=.chainguard.platform.guardener.v1alpha1.GetEntitlementRequest\x1a3.chainguard.platform.guardener.v1alpha1.Entitlement\"?\x82\xd3\xe4\x93\x02-\x12+/guardener/v1alpha1/entitlements/{group=**}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x81\x12\x12\xcf\x01\n" +
	"\x11UpdateEntitlement\x12@.chainguard.platform.guardener.v1alpha1.UpdateEntitlementRequest\x1a3.chainguard.platform.guardener.v1alpha1.Entitlement\"C\x82\xd3\xe4\x93\x020:\x01*\x1a+/guardener/v1alpha1/entitlements/{group=**}\x8a\xaf\xa8\xd2\x05\a\x12\x05\n" +
	"\x03\x80\x12\x02\x12\xf3\x03\n" +
	"\x11MigrateRepository\x12@.chainguard.platform.guardener.v1alpha1.MigrateRepositoryRequest\x1a\x1d.google.longrunning.Operation\"\xfc\x02\xcaA\x82\x01\n" +
	"?chainguard.platform.guardener.v1alpha1.MigrateOperationResponse\x12?chainguard.platform.guardener.v1alpha1.MigrateOperationMetadata\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/guardener/v1alpha1/migrate\x8a\xaf\xa8\xd2\x05\x02\x12\x00\x9a\xaf\xa8\xd2\x05\xc1\x01\n" +
	"\xb8\x01Enqueue repository migration. Set configured_migrations to run the opted-in Actions and image migrations with separate results and pull requests; omitted retains Actions-only behavior. \x00(\x010\x00\x12\x99\x02\n" +
	"\x15GetMigrationOperation\x12D.chainguard.platform.guardener.v1alpha1.GetMigrationOperationRequest\x1a\x1d.google.longrunning.Operation\"\x9a\x01\x82\xd3\xe4\x93\x022\x120/guardener/v1alpha1/{name=operations/migrate/**}\x8a\xaf\xa8\xd2\x05\x02\x12\x00\x9a\xaf\xa8\xd2\x05T\n" +
	"JGet the state of a guardener migration long-running operation by its name.\x18\x01 \x00(\x010\x00\x12\xf8\x02\n" +
	"\tListScans\x128.chainguard.platform.guardener.v1alpha1.ListScansRequest\x1a9.chainguard.platform.guardener.v1alpha1.ListScansResponse\"\xf5\x01\x82\xd3\xe4\x93\x02&\x12$/guardener/v1alpha1/{group=**}/scans\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x83\x12\x9a\xaf\xa8\xd2\x05\xb6\x01\n" +
	"\xab\x01List summaries of a group's guardener dependency scans (one per repository, newest first): scan id, repository, commit, and scan time. Resolve a summary's id with GetScan.\x18\x01 \x00(\x010\x00\x12\xbf\x02\n" +
	"\aGetScan\x126.chainguard.platform.guardener.v1alpha1.GetScanRequest\x1a,.chainguard.platform.guardener.v1alpha1.Scan\"\xcd\x01\x82\xd3\xe4\x93\x02+\x12)/guardener/v1alpha1/{group=**}/scans/{id}\x8a\xaf\xa8\xd2\x05\x06\x12\x04\n" +
	"\x02\x84\x12\x9a\xaf\xa8\xd2\x05\x89\x01\n" +
	"\x7fGet one guardener dependency scan by id: declared artifacts (purl and declaring file paths) and the relationships between them.\x18\x01 \x00(\x010\x00B\x7f\n" +
	"*com.chainguard.platform.guardener.v1alpha1B\x0eGuardenerProtoP\x01Z?chainguard.dev/sdk/proto/chainguard/platform/guardener/v1alpha1b\x06proto3"

var (
	file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescOnce sync.Once
	file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescData []byte
)

func file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescGZIP() []byte {
	file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescOnce.Do(func() {
		file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDesc), len(file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDesc)))
	})
	return file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDescData
}

var file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_chainguard_platform_guardener_v1alpha1_guardener_proto_goTypes = []any{
	(Trigger)(0),                         // 0: chainguard.platform.guardener.v1alpha1.Trigger
	(MigrationFeature)(0),                // 1: chainguard.platform.guardener.v1alpha1.MigrationFeature
	(Entitlement_RepoVisibilityScope)(0), // 2: chainguard.platform.guardener.v1alpha1.Entitlement.RepoVisibilityScope
	(*Entitlement)(nil),                  // 3: chainguard.platform.guardener.v1alpha1.Entitlement
	(*GetEntitlementRequest)(nil),        // 4: chainguard.platform.guardener.v1alpha1.GetEntitlementRequest
	(*UpdateEntitlementRequest)(nil),     // 5: chainguard.platform.guardener.v1alpha1.UpdateEntitlementRequest
	(*MigrateRepositoryRequest)(nil),     // 6: chainguard.platform.guardener.v1alpha1.MigrateRepositoryRequest
	(*MigrationFeatureResult)(nil),       // 7: chainguard.platform.guardener.v1alpha1.MigrationFeatureResult
	(*GetMigrationOperationRequest)(nil), // 8: chainguard.platform.guardener.v1alpha1.GetMigrationOperationRequest
	(*MigrateOperationMetadata)(nil),     // 9: chainguard.platform.guardener.v1alpha1.MigrateOperationMetadata
	(*MigrateOperationResponse)(nil),     // 10: chainguard.platform.guardener.v1alpha1.MigrateOperationResponse
	(*ListScansRequest)(nil),             // 11: chainguard.platform.guardener.v1alpha1.ListScansRequest
	(*ListScansResponse)(nil),            // 12: chainguard.platform.guardener.v1alpha1.ListScansResponse
	(*ScanSummary)(nil),                  // 13: chainguard.platform.guardener.v1alpha1.ScanSummary
	(*GetScanRequest)(nil),               // 14: chainguard.platform.guardener.v1alpha1.GetScanRequest
	(*Scan)(nil),                         // 15: chainguard.platform.guardener.v1alpha1.Scan
	(*ScanArtifact)(nil),                 // 16: chainguard.platform.guardener.v1alpha1.ScanArtifact
	(*ScanRelationship)(nil),             // 17: chainguard.platform.guardener.v1alpha1.ScanRelationship
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
	(*status.Status)(nil),                // 19: google.rpc.Status
	(*longrunningpb.Operation)(nil),      // 20: google.longrunning.Operation
}
var file_chainguard_platform_guardener_v1alpha1_guardener_proto_depIdxs = []int32{
	2,  // 0: chainguard.platform.guardener.v1alpha1.Entitlement.repo_visibility_scope:type_name -> chainguard.platform.guardener.v1alpha1.Entitlement.RepoVisibilityScope
	18, // 1: chainguard.platform.guardener.v1alpha1.Entitlement.create_time:type_name -> google.protobuf.Timestamp
	18, // 2: chainguard.platform.guardener.v1alpha1.Entitlement.update_time:type_name -> google.protobuf.Timestamp
	2,  // 3: chainguard.platform.guardener.v1alpha1.UpdateEntitlementRequest.repo_visibility_scope:type_name -> chainguard.platform.guardener.v1alpha1.Entitlement.RepoVisibilityScope
	1,  // 4: chainguard.platform.guardener.v1alpha1.MigrationFeatureResult.feature:type_name -> chainguard.platform.guardener.v1alpha1.MigrationFeature
	19, // 5: chainguard.platform.guardener.v1alpha1.MigrationFeatureResult.error:type_name -> google.rpc.Status
	18, // 6: chainguard.platform.guardener.v1alpha1.MigrateOperationMetadata.create_time:type_name -> google.protobuf.Timestamp
	0,  // 7: chainguard.platform.guardener.v1alpha1.MigrateOperationMetadata.trigger:type_name -> chainguard.platform.guardener.v1alpha1.Trigger
	1,  // 8: chainguard.platform.guardener.v1alpha1.MigrateOperationMetadata.feature:type_name -> chainguard.platform.guardener.v1alpha1.MigrationFeature
	7,  // 9: chainguard.platform.guardener.v1alpha1.MigrateOperationMetadata.results:type_name -> chainguard.platform.guardener.v1alpha1.MigrationFeatureResult
	7,  // 10: chainguard.platform.guardener.v1alpha1.MigrateOperationResponse.results:type_name -> chainguard.platform.guardener.v1alpha1.MigrationFeatureResult
	13, // 11: chainguard.platform.guardener.v1alpha1.ListScansResponse.scans:type_name -> chainguard.platform.guardener.v1alpha1.ScanSummary
	18, // 12: chainguard.platform.guardener.v1alpha1.ScanSummary.scan_time:type_name -> google.protobuf.Timestamp
	18, // 13: chainguard.platform.guardener.v1alpha1.Scan.scan_time:type_name -> google.protobuf.Timestamp
	16, // 14: chainguard.platform.guardener.v1alpha1.Scan.artifacts:type_name -> chainguard.platform.guardener.v1alpha1.ScanArtifact
	17, // 15: chainguard.platform.guardener.v1alpha1.Scan.relationships:type_name -> chainguard.platform.guardener.v1alpha1.ScanRelationship
	4,  // 16: chainguard.platform.guardener.v1alpha1.Guardener.GetEntitlement:input_type -> chainguard.platform.guardener.v1alpha1.GetEntitlementRequest
	5,  // 17: chainguard.platform.guardener.v1alpha1.Guardener.UpdateEntitlement:input_type -> chainguard.platform.guardener.v1alpha1.UpdateEntitlementRequest
	6,  // 18: chainguard.platform.guardener.v1alpha1.Guardener.MigrateRepository:input_type -> chainguard.platform.guardener.v1alpha1.MigrateRepositoryRequest
	8,  // 19: chainguard.platform.guardener.v1alpha1.Guardener.GetMigrationOperation:input_type -> chainguard.platform.guardener.v1alpha1.GetMigrationOperationRequest
	11, // 20: chainguard.platform.guardener.v1alpha1.Guardener.ListScans:input_type -> chainguard.platform.guardener.v1alpha1.ListScansRequest
	14, // 21: chainguard.platform.guardener.v1alpha1.Guardener.GetScan:input_type -> chainguard.platform.guardener.v1alpha1.GetScanRequest
	3,  // 22: chainguard.platform.guardener.v1alpha1.Guardener.GetEntitlement:output_type -> chainguard.platform.guardener.v1alpha1.Entitlement
	3,  // 23: chainguard.platform.guardener.v1alpha1.Guardener.UpdateEntitlement:output_type -> chainguard.platform.guardener.v1alpha1.Entitlement
	20, // 24: chainguard.platform.guardener.v1alpha1.Guardener.MigrateRepository:output_type -> google.longrunning.Operation
	20, // 25: chainguard.platform.guardener.v1alpha1.Guardener.GetMigrationOperation:output_type -> google.longrunning.Operation
	12, // 26: chainguard.platform.guardener.v1alpha1.Guardener.ListScans:output_type -> chainguard.platform.guardener.v1alpha1.ListScansResponse
	15, // 27: chainguard.platform.guardener.v1alpha1.Guardener.GetScan:output_type -> chainguard.platform.guardener.v1alpha1.Scan
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chainguard_platform_guardener_v1alpha1_guardener_proto_init() }
func file_chainguard_platform_guardener_v1alpha1_guardener_proto_init() {
	if File_chainguard_platform_guardener_v1alpha1_guardener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDesc), len(file_chainguard_platform_guardener_v1alpha1_guardener_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chainguard_platform_guardener_v1alpha1_guardener_proto_goTypes,
		DependencyIndexes: file_chainguard_platform_guardener_v1alpha1_guardener_proto_depIdxs,
		EnumInfos:         file_chainguard_platform_guardener_v1alpha1_guardener_proto_enumTypes,
		MessageInfos:      file_chainguard_platform_guardener_v1alpha1_guardener_proto_msgTypes,
	}.Build()
	File_chainguard_platform_guardener_v1alpha1_guardener_proto = out.File
	file_chainguard_platform_guardener_v1alpha1_guardener_proto_goTypes = nil
	file_chainguard_platform_guardener_v1alpha1_guardener_proto_depIdxs = nil
}
