// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: aws_marketplace_subscriptions.libraries.platform.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AWSMarketplaceSubscriptions_Create_FullMethodName = "/chainguard.platform.libraries.AWSMarketplaceSubscriptions/Create"
	AWSMarketplaceSubscriptions_Get_FullMethodName    = "/chainguard.platform.libraries.AWSMarketplaceSubscriptions/Get"
	AWSMarketplaceSubscriptions_List_FullMethodName   = "/chainguard.platform.libraries.AWSMarketplaceSubscriptions/List"
	AWSMarketplaceSubscriptions_Cancel_FullMethodName = "/chainguard.platform.libraries.AWSMarketplaceSubscriptions/Cancel"
)

// AWSMarketplaceSubscriptionsClient is the client API for AWSMarketplaceSubscriptions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AWSMarketplaceSubscriptions manages an org's subscription to Chainguard
// Libraries purchased through AWS Security Hub Extended (the AWS Marketplace).
type AWSMarketplaceSubscriptionsClient interface {
	// Create provisions a subscription for an org from an AWS Marketplace
	// registration token. aws_token is exchanged server-side and doubles
	// as an authorization gate: only a token minted by AWS Marketplace
	// resolves, so a caller without one cannot create a subscription.
	// The caller must additionally hold the create capability on parent_id.
	Create(ctx context.Context, in *CreateAWSMarketplaceSubscriptionRequest, opts ...grpc.CallOption) (*AWSMarketplaceSubscription, error)
	// Get returns a single subscription by its uidp.
	Get(ctx context.Context, in *GetAWSMarketplaceSubscriptionRequest, opts ...grpc.CallOption) (*AWSMarketplaceSubscription, error)
	// List returns the subscriptions under an org.
	List(ctx context.Context, in *AWSMarketplaceSubscriptionFilter, opts ...grpc.CallOption) (*AWSMarketplaceSubscriptionList, error)
	// Cancel unsubscribes the org's subscription on our side: it stops future
	// metering and removes the associated Libraries entitlements, moving the
	// subscription to UNSUBSCRIBED. The AWS Marketplace subscription itself is
	// unaffected (AWS has no partner-initiated cancellation); the record is
	// retained for billing history.
	Cancel(ctx context.Context, in *CancelAWSMarketplaceSubscriptionRequest, opts ...grpc.CallOption) (*AWSMarketplaceSubscription, error)
}

type aWSMarketplaceSubscriptionsClient struct {
	cc grpc.ClientConnInterface
}

func NewAWSMarketplaceSubscriptionsClient(cc grpc.ClientConnInterface) AWSMarketplaceSubscriptionsClient {
	return &aWSMarketplaceSubscriptionsClient{cc}
}

func (c *aWSMarketplaceSubscriptionsClient) Create(ctx context.Context, in *CreateAWSMarketplaceSubscriptionRequest, opts ...grpc.CallOption) (*AWSMarketplaceSubscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AWSMarketplaceSubscription)
	err := c.cc.Invoke(ctx, AWSMarketplaceSubscriptions_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSMarketplaceSubscriptionsClient) Get(ctx context.Context, in *GetAWSMarketplaceSubscriptionRequest, opts ...grpc.CallOption) (*AWSMarketplaceSubscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AWSMarketplaceSubscription)
	err := c.cc.Invoke(ctx, AWSMarketplaceSubscriptions_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSMarketplaceSubscriptionsClient) List(ctx context.Context, in *AWSMarketplaceSubscriptionFilter, opts ...grpc.CallOption) (*AWSMarketplaceSubscriptionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AWSMarketplaceSubscriptionList)
	err := c.cc.Invoke(ctx, AWSMarketplaceSubscriptions_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSMarketplaceSubscriptionsClient) Cancel(ctx context.Context, in *CancelAWSMarketplaceSubscriptionRequest, opts ...grpc.CallOption) (*AWSMarketplaceSubscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AWSMarketplaceSubscription)
	err := c.cc.Invoke(ctx, AWSMarketplaceSubscriptions_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AWSMarketplaceSubscriptionsServer is the server API for AWSMarketplaceSubscriptions service.
// All implementations must embed UnimplementedAWSMarketplaceSubscriptionsServer
// for forward compatibility.
//
// AWSMarketplaceSubscriptions manages an org's subscription to Chainguard
// Libraries purchased through AWS Security Hub Extended (the AWS Marketplace).
type AWSMarketplaceSubscriptionsServer interface {
	// Create provisions a subscription for an org from an AWS Marketplace
	// registration token. aws_token is exchanged server-side and doubles
	// as an authorization gate: only a token minted by AWS Marketplace
	// resolves, so a caller without one cannot create a subscription.
	// The caller must additionally hold the create capability on parent_id.
	Create(context.Context, *CreateAWSMarketplaceSubscriptionRequest) (*AWSMarketplaceSubscription, error)
	// Get returns a single subscription by its uidp.
	Get(context.Context, *GetAWSMarketplaceSubscriptionRequest) (*AWSMarketplaceSubscription, error)
	// List returns the subscriptions under an org.
	List(context.Context, *AWSMarketplaceSubscriptionFilter) (*AWSMarketplaceSubscriptionList, error)
	// Cancel unsubscribes the org's subscription on our side: it stops future
	// metering and removes the associated Libraries entitlements, moving the
	// subscription to UNSUBSCRIBED. The AWS Marketplace subscription itself is
	// unaffected (AWS has no partner-initiated cancellation); the record is
	// retained for billing history.
	Cancel(context.Context, *CancelAWSMarketplaceSubscriptionRequest) (*AWSMarketplaceSubscription, error)
	mustEmbedUnimplementedAWSMarketplaceSubscriptionsServer()
}

// UnimplementedAWSMarketplaceSubscriptionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAWSMarketplaceSubscriptionsServer struct{}

func (UnimplementedAWSMarketplaceSubscriptionsServer) Create(context.Context, *CreateAWSMarketplaceSubscriptionRequest) (*AWSMarketplaceSubscription, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAWSMarketplaceSubscriptionsServer) Get(context.Context, *GetAWSMarketplaceSubscriptionRequest) (*AWSMarketplaceSubscription, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAWSMarketplaceSubscriptionsServer) List(context.Context, *AWSMarketplaceSubscriptionFilter) (*AWSMarketplaceSubscriptionList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAWSMarketplaceSubscriptionsServer) Cancel(context.Context, *CancelAWSMarketplaceSubscriptionRequest) (*AWSMarketplaceSubscription, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedAWSMarketplaceSubscriptionsServer) mustEmbedUnimplementedAWSMarketplaceSubscriptionsServer() {
}
func (UnimplementedAWSMarketplaceSubscriptionsServer) testEmbeddedByValue() {}

// UnsafeAWSMarketplaceSubscriptionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AWSMarketplaceSubscriptionsServer will
// result in compilation errors.
type UnsafeAWSMarketplaceSubscriptionsServer interface {
	mustEmbedUnimplementedAWSMarketplaceSubscriptionsServer()
}

func RegisterAWSMarketplaceSubscriptionsServer(s grpc.ServiceRegistrar, srv AWSMarketplaceSubscriptionsServer) {
	// If the following call panics, it indicates UnimplementedAWSMarketplaceSubscriptionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AWSMarketplaceSubscriptions_ServiceDesc, srv)
}

func _AWSMarketplaceSubscriptions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAWSMarketplaceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSMarketplaceSubscriptionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AWSMarketplaceSubscriptions_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSMarketplaceSubscriptionsServer).Create(ctx, req.(*CreateAWSMarketplaceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSMarketplaceSubscriptions_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAWSMarketplaceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSMarketplaceSubscriptionsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AWSMarketplaceSubscriptions_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSMarketplaceSubscriptionsServer).Get(ctx, req.(*GetAWSMarketplaceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSMarketplaceSubscriptions_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AWSMarketplaceSubscriptionFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSMarketplaceSubscriptionsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AWSMarketplaceSubscriptions_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSMarketplaceSubscriptionsServer).List(ctx, req.(*AWSMarketplaceSubscriptionFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSMarketplaceSubscriptions_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAWSMarketplaceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSMarketplaceSubscriptionsServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AWSMarketplaceSubscriptions_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSMarketplaceSubscriptionsServer).Cancel(ctx, req.(*CancelAWSMarketplaceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AWSMarketplaceSubscriptions_ServiceDesc is the grpc.ServiceDesc for AWSMarketplaceSubscriptions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AWSMarketplaceSubscriptions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.platform.libraries.AWSMarketplaceSubscriptions",
	HandlerType: (*AWSMarketplaceSubscriptionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AWSMarketplaceSubscriptions_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AWSMarketplaceSubscriptions_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AWSMarketplaceSubscriptions_List_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _AWSMarketplaceSubscriptions_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aws_marketplace_subscriptions.libraries.platform.proto",
}
