// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: actions.platform.proto

package v1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizeWithOIDCRequest carries no token. The OIDC ID token is
// read from the `Authorization: Bearer <jwt>` gRPC metadata header.
// The set of accepted audiences is fixed by the server; the caller
// cannot influence it.
type AuthorizeWithOIDCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeWithOIDCRequest) Reset() {
	*x = AuthorizeWithOIDCRequest{}
	mi := &file_actions_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeWithOIDCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeWithOIDCRequest) ProtoMessage() {}

func (x *AuthorizeWithOIDCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeWithOIDCRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeWithOIDCRequest) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{0}
}

// IssueChallengeRequest names the GitHub Actions run for which a
// challenge cert is being requested. The server treats these as
// claims to bind into the leaf cert's URI SAN; trust does not arrive
// until the subsequent VerifyChallenge call confirms the cert
// appeared as an artifact in that run's actual artifact listing.
type IssueChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repository is the owner/repo slug, e.g. "chainguard-dev/mono".
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// run_id is the workflow run ID (numeric, as a string).
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// run_attempt is the workflow run attempt number (numeric, as a
	// string).
	RunAttempt    string `protobuf:"bytes,3,opt,name=run_attempt,json=runAttempt,proto3" json:"run_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueChallengeRequest) Reset() {
	*x = IssueChallengeRequest{}
	mi := &file_actions_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueChallengeRequest) ProtoMessage() {}

func (x *IssueChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueChallengeRequest.ProtoReflect.Descriptor instead.
func (*IssueChallengeRequest) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{1}
}

func (x *IssueChallengeRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *IssueChallengeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *IssueChallengeRequest) GetRunAttempt() string {
	if x != nil {
		return x.RunAttempt
	}
	return ""
}

type IssueChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cert is a PEM-encoded X.509 leaf certificate signed by the
	// server's CA. The workflow writes this PEM into a GitHub Actions
	// artifact whose name starts with `chainguard-actions-client`. The
	// cert encodes the run identity in a URI SAN; only the server's
	// signing key can have produced it. NotAfter and the serial number
	// are encoded inside the cert — clients extract them by parsing.
	Cert          string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueChallengeResponse) Reset() {
	*x = IssueChallengeResponse{}
	mi := &file_actions_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueChallengeResponse) ProtoMessage() {}

func (x *IssueChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueChallengeResponse.ProtoReflect.Descriptor instead.
func (*IssueChallengeResponse) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{2}
}

func (x *IssueChallengeResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

// VerifyChallengeRequest names the run to verify. The server lists
// the run's GitHub Actions artifacts, downloads any whose name starts
// with `chainguard-actions-client`, and looks for one whose
// certificate is signed by the server's CA and whose URI SAN matches
// this run identity. The client cannot influence which artifact is
// checked.
type VerifyChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repository is the owner/repo slug, matching the IssueChallenge
	// call.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// run_id is the workflow run ID (numeric, as a string).
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// run_attempt is the workflow run attempt number.
	RunAttempt    string `protobuf:"bytes,3,opt,name=run_attempt,json=runAttempt,proto3" json:"run_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChallengeRequest) Reset() {
	*x = VerifyChallengeRequest{}
	mi := &file_actions_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChallengeRequest) ProtoMessage() {}

func (x *VerifyChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChallengeRequest.ProtoReflect.Descriptor instead.
func (*VerifyChallengeRequest) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyChallengeRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *VerifyChallengeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *VerifyChallengeRequest) GetRunAttempt() string {
	if x != nil {
		return x.RunAttempt
	}
	return ""
}

// GetCACertRequest carries no fields. The server's CA is fixed at
// deploy time; the caller cannot select among CAs.
type GetCACertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCACertRequest) Reset() {
	*x = GetCACertRequest{}
	mi := &file_actions_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCACertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCACertRequest) ProtoMessage() {}

func (x *GetCACertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCACertRequest.ProtoReflect.Descriptor instead.
func (*GetCACertRequest) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{4}
}

// CACertResponse carries the server's active signer CA cert.
type CACertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ca_cert is the PEM-encoded X.509 CA certificate (one
	// `CERTIFICATE` block).
	CaCert        string `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CACertResponse) Reset() {
	*x = CACertResponse{}
	mi := &file_actions_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CACertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CACertResponse) ProtoMessage() {}

func (x *CACertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CACertResponse.ProtoReflect.Descriptor instead.
func (*CACertResponse) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{5}
}

func (x *CACertResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

// GetTrustedKeysRequest carries no fields.
type GetTrustedKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrustedKeysRequest) Reset() {
	*x = GetTrustedKeysRequest{}
	mi := &file_actions_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustedKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustedKeysRequest) ProtoMessage() {}

func (x *GetTrustedKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustedKeysRequest.ProtoReflect.Descriptor instead.
func (*GetTrustedKeysRequest) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{6}
}

// TrustedKeysResponse lists every public key currently trusted for
// attestation-leaf verification. During a key-rotation overlap the
// list contains both the new and the previous signing key; once the
// previous key is dropped from CHALLENGE_KMS_TRUSTED_VERSIONS on the
// next deploy, only the new key remains.
type TrustedKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_keys is a sequence of PEM-encoded PKIX `PUBLIC KEY` blocks
	// concatenated together. Order is not significant.
	PublicKeys    string `protobuf:"bytes,1,opt,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustedKeysResponse) Reset() {
	*x = TrustedKeysResponse{}
	mi := &file_actions_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedKeysResponse) ProtoMessage() {}

func (x *TrustedKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedKeysResponse.ProtoReflect.Descriptor instead.
func (*TrustedKeysResponse) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{7}
}

func (x *TrustedKeysResponse) GetPublicKeys() string {
	if x != nil {
		return x.PublicKeys
	}
	return ""
}

// AuthorizationResponse describes the outcome of a *successful*
// authorization check. Failure is signaled by a non-OK gRPC status
// (codes.Unauthenticated); a returned message always represents
// success and always carries claims. The body deliberately does NOT
// distinguish among failure modes — see the RPC definitions for the
// privacy rationale.
type AuthorizationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// claims echoes the verified GitHub identity (subset of GitHub's
	// OIDC claim names). For the OIDC path, claims come from the
	// verified token. For the challenge path, claims come from the
	// WorkflowRun fetched from the GitHub API at verify time — not from
	// the IssueChallenge inputs.
	Claims        map[string]string `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationResponse) Reset() {
	*x = AuthorizationResponse{}
	mi := &file_actions_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResponse) ProtoMessage() {}

func (x *AuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorizationResponse) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

// RecordRequest names the GitHub repository whose use of the service
// is being recorded. Whose value the server actually trusts depends
// on the optional OIDC bearer token:
//
//   - Verified call (valid bearer presented): the `repository` field
//     is IGNORED. The server takes the repository slug from the
//     verified token's `repository` claim instead — that value is
//     authoritative, and accepting a request-supplied one would just
//     create a way to lie.
//   - Unverified call (no bearer): the `repository` field is REQUIRED
//     and is taken as-is. The recorded event is marked unverified.
//
// There are no other caller-supplied fields — no metrics, no
// attributes, no free-form text. The recording is internal: the
// server keeps a usage record per repository (today via structured
// logging), and the response is empty.
type RecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repository is the owner/repo slug, e.g. "chainguard-dev/mono".
	// Required on unverified calls; ignored on verified calls. Server-
	// enforced caps: non-empty, ≤256 bytes, must contain a single "/"
	// separating non-empty owner and repo segments.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_actions_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{9}
}

func (x *RecordRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

// RecordResponse is empty on success. Failure is signaled by a
// non-OK gRPC status.
type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_actions_platform_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actions_platform_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_actions_platform_proto_rawDescGZIP(), []int{10}
}

var File_actions_platform_proto protoreflect.FileDescriptor

const file_actions_platform_proto_rawDesc = "" +
	"\n" +
	"\x16actions.platform.proto\x12\x1bchainguard.platform.actions\x1a\x1cgoogle/api/annotations.proto\x1a\x16annotations/auth.proto\"\x1a\n" +
	"\x18AuthorizeWithOIDCRequest\"o\n" +
	"\x15IssueChallengeRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vrun_attempt\x18\x03 \x01(\tR\n" +
	"runAttempt\",\n" +
	"\x16IssueChallengeResponse\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\tR\x04cert\"p\n" +
	"\x16VerifyChallengeRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vrun_attempt\x18\x03 \x01(\tR\n" +
	"runAttempt\"\x12\n" +
	"\x10GetCACertRequest\")\n" +
	"\x0eCACertResponse\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\tR\x06caCert\"\x17\n" +
	"\x15GetTrustedKeysRequest\"6\n" +
	"\x13TrustedKeysResponse\x12\x1f\n" +
	"\vpublic_keys\x18\x01 \x01(\tR\n" +
	"publicKeys\"\xaa\x01\n" +
	"\x15AuthorizationResponse\x12V\n" +
	"\x06claims\x18\x01 \x03(\v2>.chainguard.platform.actions.AuthorizationResponse.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\rRecordRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"\x10\n" +
	"\x0eRecordResponse2\xcd\x06\n" +
	"\x14ActionsAuthorization\x12\xad\x01\n" +
	"\x11AuthorizeWithOIDC\x125.chainguard.platform.actions.AuthorizeWithOIDCRequest\x1a2.chainguard.platform.actions.AuthorizationResponse\"-\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/actions/v1/authorize/oidc\x8a\xaf\xa8\xd2\x05\x02\n" +
	"\x00\x12\xa9\x01\n" +
	"\x0eIssueChallenge\x122.chainguard.platform.actions.IssueChallengeRequest\x1a3.chainguard.platform.actions.IssueChallengeResponse\".\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/actions/v1/challenge/issue\x8a\xaf\xa8\xd2\x05\x02\n" +
	"\x00\x12\xab\x01\n" +
	"\x0fVerifyChallenge\x123.chainguard.platform.actions.VerifyChallengeRequest\x1a2.chainguard.platform.actions.AuthorizationResponse\"/\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/actions/v1/challenge/verify\x8a\xaf\xa8\xd2\x05\x02\n" +
	"\x00\x12\x87\x01\n" +
	"\tGetCACert\x12-.chainguard.platform.actions.GetCACertRequest\x1a+.chainguard.platform.actions.CACertResponse\"\x1e\x82\xd3\xe4\x93\x02\x10\x12\x0e/actions/v1/ca\x8a\xaf\xa8\xd2\x05\x02\n" +
	"\x00\x12\xa0\x01\n" +
	"\x0eGetTrustedKeys\x122.chainguard.platform.actions.GetTrustedKeysRequest\x1a0.chainguard.platform.actions.TrustedKeysResponse\"(\x82\xd3\xe4\x93\x02\x1a\x12\x18/actions/v1/trusted-keys\x8a\xaf\xa8\xd2\x05\x02\n" +
	"\x002\x94\x01\n" +
	"\aActions\x12\x88\x01\n" +
	"\x06Record\x12*.chainguard.platform.actions.RecordRequest\x1a+.chainguard.platform.actions.RecordResponse\"%\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/actions/v1/record\x8a\xaf\xa8\xd2\x05\x02\n" +
	"\x00B.Z,chainguard.dev/sdk/proto/platform/actions/v1b\x06proto3"

var (
	file_actions_platform_proto_rawDescOnce sync.Once
	file_actions_platform_proto_rawDescData []byte
)

func file_actions_platform_proto_rawDescGZIP() []byte {
	file_actions_platform_proto_rawDescOnce.Do(func() {
		file_actions_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actions_platform_proto_rawDesc), len(file_actions_platform_proto_rawDesc)))
	})
	return file_actions_platform_proto_rawDescData
}

var file_actions_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_actions_platform_proto_goTypes = []any{
	(*AuthorizeWithOIDCRequest)(nil), // 0: chainguard.platform.actions.AuthorizeWithOIDCRequest
	(*IssueChallengeRequest)(nil),    // 1: chainguard.platform.actions.IssueChallengeRequest
	(*IssueChallengeResponse)(nil),   // 2: chainguard.platform.actions.IssueChallengeResponse
	(*VerifyChallengeRequest)(nil),   // 3: chainguard.platform.actions.VerifyChallengeRequest
	(*GetCACertRequest)(nil),         // 4: chainguard.platform.actions.GetCACertRequest
	(*CACertResponse)(nil),           // 5: chainguard.platform.actions.CACertResponse
	(*GetTrustedKeysRequest)(nil),    // 6: chainguard.platform.actions.GetTrustedKeysRequest
	(*TrustedKeysResponse)(nil),      // 7: chainguard.platform.actions.TrustedKeysResponse
	(*AuthorizationResponse)(nil),    // 8: chainguard.platform.actions.AuthorizationResponse
	(*RecordRequest)(nil),            // 9: chainguard.platform.actions.RecordRequest
	(*RecordResponse)(nil),           // 10: chainguard.platform.actions.RecordResponse
	nil,                              // 11: chainguard.platform.actions.AuthorizationResponse.ClaimsEntry
}
var file_actions_platform_proto_depIdxs = []int32{
	11, // 0: chainguard.platform.actions.AuthorizationResponse.claims:type_name -> chainguard.platform.actions.AuthorizationResponse.ClaimsEntry
	0,  // 1: chainguard.platform.actions.ActionsAuthorization.AuthorizeWithOIDC:input_type -> chainguard.platform.actions.AuthorizeWithOIDCRequest
	1,  // 2: chainguard.platform.actions.ActionsAuthorization.IssueChallenge:input_type -> chainguard.platform.actions.IssueChallengeRequest
	3,  // 3: chainguard.platform.actions.ActionsAuthorization.VerifyChallenge:input_type -> chainguard.platform.actions.VerifyChallengeRequest
	4,  // 4: chainguard.platform.actions.ActionsAuthorization.GetCACert:input_type -> chainguard.platform.actions.GetCACertRequest
	6,  // 5: chainguard.platform.actions.ActionsAuthorization.GetTrustedKeys:input_type -> chainguard.platform.actions.GetTrustedKeysRequest
	9,  // 6: chainguard.platform.actions.Actions.Record:input_type -> chainguard.platform.actions.RecordRequest
	8,  // 7: chainguard.platform.actions.ActionsAuthorization.AuthorizeWithOIDC:output_type -> chainguard.platform.actions.AuthorizationResponse
	2,  // 8: chainguard.platform.actions.ActionsAuthorization.IssueChallenge:output_type -> chainguard.platform.actions.IssueChallengeResponse
	8,  // 9: chainguard.platform.actions.ActionsAuthorization.VerifyChallenge:output_type -> chainguard.platform.actions.AuthorizationResponse
	5,  // 10: chainguard.platform.actions.ActionsAuthorization.GetCACert:output_type -> chainguard.platform.actions.CACertResponse
	7,  // 11: chainguard.platform.actions.ActionsAuthorization.GetTrustedKeys:output_type -> chainguard.platform.actions.TrustedKeysResponse
	10, // 12: chainguard.platform.actions.Actions.Record:output_type -> chainguard.platform.actions.RecordResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_actions_platform_proto_init() }
func file_actions_platform_proto_init() {
	if File_actions_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actions_platform_proto_rawDesc), len(file_actions_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_actions_platform_proto_goTypes,
		DependencyIndexes: file_actions_platform_proto_depIdxs,
		MessageInfos:      file_actions_platform_proto_msgTypes,
	}.Build()
	File_actions_platform_proto = out.File
	file_actions_platform_proto_goTypes = nil
	file_actions_platform_proto_depIdxs = nil
}
