// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: uidp.platform.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UIDPFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ancestors_of are groups reachable by repeated proceeding from child to parent.
	AncestorsOf string `protobuf:"bytes,1,opt,name=ancestors_of,json=ancestorsOf,proto3" json:"ancestors_of,omitempty"`
	// descendants_of are groups reachable by repeated proceeding from parent to child.
	DescendantsOf string `protobuf:"bytes,2,opt,name=descendants_of,json=descendantsOf,proto3" json:"descendants_of,omitempty"`
	// children_of are groups reachable by directly proceeding from parent to children.
	ChildrenOf string `protobuf:"bytes,3,opt,name=children_of,json=childrenOf,proto3" json:"children_of,omitempty"`
	// in_root resticts responses to root level resources (organizations, user identities)
	InRoot bool `protobuf:"varint,4,opt,name=in_root,json=inRoot,proto3" json:"in_root,omitempty"`
}

func (x *UIDPFilter) Reset() {
	*x = UIDPFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uidp_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIDPFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIDPFilter) ProtoMessage() {}

func (x *UIDPFilter) ProtoReflect() protoreflect.Message {
	mi := &file_uidp_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIDPFilter.ProtoReflect.Descriptor instead.
func (*UIDPFilter) Descriptor() ([]byte, []int) {
	return file_uidp_platform_proto_rawDescGZIP(), []int{0}
}

func (x *UIDPFilter) GetAncestorsOf() string {
	if x != nil {
		return x.AncestorsOf
	}
	return ""
}

func (x *UIDPFilter) GetDescendantsOf() string {
	if x != nil {
		return x.DescendantsOf
	}
	return ""
}

func (x *UIDPFilter) GetChildrenOf() string {
	if x != nil {
		return x.ChildrenOf
	}
	return ""
}

func (x *UIDPFilter) GetInRoot() bool {
	if x != nil {
		return x.InRoot
	}
	return false
}

var File_uidp_platform_proto protoreflect.FileDescriptor

var file_uidp_platform_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x69, 0x64, 0x70, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x55, 0x49, 0x44, 0x50, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x73, 0x5f, 0x6f, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x73, 0x4f, 0x66, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x61, 0x6e,
	0x74, 0x73, 0x5f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x73,
	0x63, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x74, 0x73, 0x4f, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x4f, 0x66, 0x12, 0x17, 0x0a, 0x07, 0x69,
	0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e,
	0x52, 0x6f, 0x6f, 0x74, 0x42, 0x6f, 0x0a, 0x25, 0x64, 0x65, 0x76, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x17, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x55, 0x49, 0x44,
	0x50, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uidp_platform_proto_rawDescOnce sync.Once
	file_uidp_platform_proto_rawDescData = file_uidp_platform_proto_rawDesc
)

func file_uidp_platform_proto_rawDescGZIP() []byte {
	file_uidp_platform_proto_rawDescOnce.Do(func() {
		file_uidp_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_uidp_platform_proto_rawDescData)
	})
	return file_uidp_platform_proto_rawDescData
}

var file_uidp_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_uidp_platform_proto_goTypes = []interface{}{
	(*UIDPFilter)(nil), // 0: chainguard.platform.common.UIDPFilter
}
var file_uidp_platform_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uidp_platform_proto_init() }
func file_uidp_platform_proto_init() {
	if File_uidp_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uidp_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIDPFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uidp_platform_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uidp_platform_proto_goTypes,
		DependencyIndexes: file_uidp_platform_proto_depIdxs,
		MessageInfos:      file_uidp_platform_proto_msgTypes,
	}.Build()
	File_uidp_platform_proto = out.File
	file_uidp_platform_proto_rawDesc = nil
	file_uidp_platform_proto_goTypes = nil
	file_uidp_platform_proto_depIdxs = nil
}
