// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apk.platform.proto

package v1

import (
	_ "chainguard.dev/sdk/proto/annotations"
	v1 "chainguard.dev/sdk/proto/platform/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APKFilter is a filter for APKs.
type APKFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uidp  *v1.UIDPFilter         `protobuf:"bytes,1,opt,name=uidp,proto3" json:"uidp,omitempty"`
	// A name to filter by.
	PackageName string `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// An architecture to filter by (e.g., x86_64 or aarch64).
	Architecture string `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Only return the most recently updated version of each package/architecture.
	MostRecentlyUpdated bool `protobuf:"varint,4,opt,name=most_recently_updated,json=mostRecentlyUpdated,proto3" json:"most_recently_updated,omitempty"`
	// Filter by origin package. Returns all packages (including subpackages)
	// that have this origin. For origin packages, origin equals package_name.
	Origin string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	// Pagination: Maximum number of results to return per page.
	// When set to 0 and page_token is empty, all results are returned (backward compatible).
	// Default: 50, Maximum: 200
	PageSize int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination: Opaque token for retrieving the next page of results.
	// Use the value from next_page_token in the previous response.
	PageToken string `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Order results by field. Format: "field [asc|desc]"
	// Supported fields: "uid", "package_name", "build_time"
	// Examples: "package_name asc", "build_time desc"
	// Default: sorted by uid
	OrderBy string `protobuf:"bytes,8,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Number of results to skip (for random-access pagination).
	// Applied after cursor positioning.
	Skip          int32 `protobuf:"varint,9,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APKFilter) Reset() {
	*x = APKFilter{}
	mi := &file_apk_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APKFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APKFilter) ProtoMessage() {}

func (x *APKFilter) ProtoReflect() protoreflect.Message {
	mi := &file_apk_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APKFilter.ProtoReflect.Descriptor instead.
func (*APKFilter) Descriptor() ([]byte, []int) {
	return file_apk_platform_proto_rawDescGZIP(), []int{0}
}

func (x *APKFilter) GetUidp() *v1.UIDPFilter {
	if x != nil {
		return x.Uidp
	}
	return nil
}

func (x *APKFilter) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *APKFilter) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *APKFilter) GetMostRecentlyUpdated() bool {
	if x != nil {
		return x.MostRecentlyUpdated
	}
	return false
}

func (x *APKFilter) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *APKFilter) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *APKFilter) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *APKFilter) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *APKFilter) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// APKList is a list of APKs.
type APKList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The APKs returned by the list request.
	Items []*APKPackage `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Pagination: Token for retrieving the next page of results.
	// Empty if there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of APKs matching the filter.
	// Useful for displaying "Page 1 of N" in UIs.
	TotalCount int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Number of results that were skipped to reach this page.
	// This accumulates across pages when using skip parameter.
	Skipped       int32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APKList) Reset() {
	*x = APKList{}
	mi := &file_apk_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APKList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APKList) ProtoMessage() {}

func (x *APKList) ProtoReflect() protoreflect.Message {
	mi := &file_apk_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APKList.ProtoReflect.Descriptor instead.
func (*APKList) Descriptor() ([]byte, []int) {
	return file_apk_platform_proto_rawDescGZIP(), []int{1}
}

func (x *APKList) GetItems() []*APKPackage {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *APKList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *APKList) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *APKList) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

// APKPackage is an APK package and its metadata.
//
// An APK can be downloaded by requesting
// https://apk.cgr.dev/{group}/{arch}/{pkgname}-{pkgver}.apk
// with suitable credentials.
//
// The fields 10+ are the fields that make up the APKINDEX format
// from here: https://wiki.alpinelinux.org/wiki/Apk_spec#APKINDEX_Format
type APKPackage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id, identifier of this APK, a UIDP under a Group.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Checksum, the checksum of the package.
	Checksum []byte `protobuf:"bytes,10,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Package name, the name of the package.
	PackageName string `protobuf:"bytes,11,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// Package version, the version of the package (e.g., 1.2.3-r4).
	Version string `protobuf:"bytes,12,opt,name=version,proto3" json:"version,omitempty"`
	// Package architecture, the architecture of the package (e.g., x86_64 or
	// aarch64).
	Architecture string `protobuf:"bytes,13,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Package size, the size of the package in bytes.
	Size uint64 `protobuf:"varint,14,opt,name=size,proto3" json:"size,omitempty"`
	// Installed size, the size of the package when installed in bytes.
	InstalledSize uint64 `protobuf:"varint,15,opt,name=installed_size,json=installedSize,proto3" json:"installed_size,omitempty"`
	// Package description, a description of the package.
	Description string `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	// Package URL, a URL for the package.
	Url string `protobuf:"bytes,17,opt,name=url,proto3" json:"url,omitempty"`
	// Package license, the license of the package.
	License string `protobuf:"bytes,18,opt,name=license,proto3" json:"license,omitempty"`
	// Package origin, the origin of the package (if the package is a subpackage).
	Origin string `protobuf:"bytes,19,opt,name=origin,proto3" json:"origin,omitempty"`
	// Package maintainer, unused.
	Maintainer string `protobuf:"bytes,20,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	// Package build time, the time the package was built.
	BuildTime *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	// Package commit, the commit of the package.
	RepoCommit string `protobuf:"bytes,22,opt,name=repo_commit,json=repoCommit,proto3" json:"repo_commit,omitempty"`
	// Package provider priority, the priority of the package provider.
	// If multiple packages provide the same virtual package, the package
	// with the highest provider priority is selected.
	ProviderPriority uint64 `protobuf:"varint,23,opt,name=provider_priority,json=providerPriority,proto3" json:"provider_priority,omitempty"`
	// Package depend, the direct runtime dependencies of the package.
	Depend []string `protobuf:"bytes,24,rep,name=depend,proto3" json:"depend,omitempty"`
	// Package provides, the virtual packages provided by the package.
	Provides []string `protobuf:"bytes,25,rep,name=provides,proto3" json:"provides,omitempty"`
	// Package install if, the conditions under which the package is installed.
	InstallIf     []string `protobuf:"bytes,26,rep,name=install_if,json=installIf,proto3" json:"install_if,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APKPackage) Reset() {
	*x = APKPackage{}
	mi := &file_apk_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APKPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APKPackage) ProtoMessage() {}

func (x *APKPackage) ProtoReflect() protoreflect.Message {
	mi := &file_apk_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APKPackage.ProtoReflect.Descriptor instead.
func (*APKPackage) Descriptor() ([]byte, []int) {
	return file_apk_platform_proto_rawDescGZIP(), []int{2}
}

func (x *APKPackage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APKPackage) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *APKPackage) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *APKPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *APKPackage) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *APKPackage) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *APKPackage) GetInstalledSize() uint64 {
	if x != nil {
		return x.InstalledSize
	}
	return 0
}

func (x *APKPackage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APKPackage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *APKPackage) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *APKPackage) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *APKPackage) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *APKPackage) GetBuildTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildTime
	}
	return nil
}

func (x *APKPackage) GetRepoCommit() string {
	if x != nil {
		return x.RepoCommit
	}
	return ""
}

func (x *APKPackage) GetProviderPriority() uint64 {
	if x != nil {
		return x.ProviderPriority
	}
	return 0
}

func (x *APKPackage) GetDepend() []string {
	if x != nil {
		return x.Depend
	}
	return nil
}

func (x *APKPackage) GetProvides() []string {
	if x != nil {
		return x.Provides
	}
	return nil
}

func (x *APKPackage) GetInstallIf() []string {
	if x != nil {
		return x.InstallIf
	}
	return nil
}

// APKSummaryFilter is the request message for ListAPKSummaries.
type APKSummaryFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uidp  *v1.UIDPFilter         `protobuf:"bytes,1,opt,name=uidp,proto3" json:"uidp,omitempty"`
	// query is a prefix match on package_name (e.g. "bash" matches "bash",
	// "bash-completion", etc.). When empty, all packages are returned.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// architecture optionally restricts results to a specific architecture.
	Architecture string `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// origin optionally restricts results to packages with the given origin.
	Origin string `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	// page_size is the maximum number of summaries to return per page.
	// Default: 50, Maximum: 200.
	PageSize int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token is the opaque token returned by a previous ListAPKSummaries
	// call. Provide it to retrieve the next page of results.
	PageToken string `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// order_by controls the sort order. Format: "field [asc|desc]".
	// Supported fields: "package_name", "build_time".
	// Default: "package_name asc".
	OrderBy string `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Number of results to skip (for random-access pagination).
	// Applied after cursor positioning.
	Skip          int32 `protobuf:"varint,8,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APKSummaryFilter) Reset() {
	*x = APKSummaryFilter{}
	mi := &file_apk_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APKSummaryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APKSummaryFilter) ProtoMessage() {}

func (x *APKSummaryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_apk_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APKSummaryFilter.ProtoReflect.Descriptor instead.
func (*APKSummaryFilter) Descriptor() ([]byte, []int) {
	return file_apk_platform_proto_rawDescGZIP(), []int{3}
}

func (x *APKSummaryFilter) GetUidp() *v1.UIDPFilter {
	if x != nil {
		return x.Uidp
	}
	return nil
}

func (x *APKSummaryFilter) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *APKSummaryFilter) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *APKSummaryFilter) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *APKSummaryFilter) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *APKSummaryFilter) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *APKSummaryFilter) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *APKSummaryFilter) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// APKPackageSummary is a single entry in a ListAPKSummaries response.
// It describes one package name with its most recently updated version.
type APKPackageSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// package_name is the base package name (e.g. "bash").
	PackageName string `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// latest_version is the version string of the most recently updated version.
	LatestVersion string `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// architectures is a comma-separated list of all architectures available
	// for the latest version (e.g. "aarch64, x86_64").
	Architectures string `protobuf:"bytes,3,opt,name=architectures,proto3" json:"architectures,omitempty"`
	// description is a short human-readable description of the package.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// license is the SPDX license identifier for the package.
	License string `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	// origin is the origin package name (equals package_name for main packages).
	Origin string `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	// build_time is the build timestamp of the latest version.
	BuildTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APKPackageSummary) Reset() {
	*x = APKPackageSummary{}
	mi := &file_apk_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APKPackageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APKPackageSummary) ProtoMessage() {}

func (x *APKPackageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_apk_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APKPackageSummary.ProtoReflect.Descriptor instead.
func (*APKPackageSummary) Descriptor() ([]byte, []int) {
	return file_apk_platform_proto_rawDescGZIP(), []int{4}
}

func (x *APKPackageSummary) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *APKPackageSummary) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *APKPackageSummary) GetArchitectures() string {
	if x != nil {
		return x.Architectures
	}
	return ""
}

func (x *APKPackageSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APKPackageSummary) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *APKPackageSummary) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *APKPackageSummary) GetBuildTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildTime
	}
	return nil
}

// APKPackageSummaryList is the response message for ListAPKSummaries.
type APKPackageSummaryList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the list of package summaries matching the request.
	Items []*APKPackageSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// next_page_token is the token for retrieving the next page of results.
	// Empty if there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// total_count is the total number of packages matching the filter.
	TotalCount int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// skipped is the total number of results skipped to reach this page.
	// This accumulates across pages when using the skip parameter.
	Skipped       int32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APKPackageSummaryList) Reset() {
	*x = APKPackageSummaryList{}
	mi := &file_apk_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APKPackageSummaryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APKPackageSummaryList) ProtoMessage() {}

func (x *APKPackageSummaryList) ProtoReflect() protoreflect.Message {
	mi := &file_apk_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APKPackageSummaryList.ProtoReflect.Descriptor instead.
func (*APKPackageSummaryList) Descriptor() ([]byte, []int) {
	return file_apk_platform_proto_rawDescGZIP(), []int{5}
}

func (x *APKPackageSummaryList) GetItems() []*APKPackageSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *APKPackageSummaryList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *APKPackageSummaryList) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *APKPackageSummaryList) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

var File_apk_platform_proto protoreflect.FileDescriptor

const file_apk_platform_proto_rawDesc = "" +
	"\n" +
	"\x12apk.platform.proto\x12\x17chainguard.platform.apk\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16annotations/auth.proto\x1a&platform/common/v1/uidp.platform.proto\"\xc5\x02\n" +
	"\tAPKFilter\x12:\n" +
	"\x04uidp\x18\x01 \x01(\v2&.chainguard.platform.common.UIDPFilterR\x04uidp\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x122\n" +
	"\x15most_recently_updated\x18\x04 \x01(\bR\x13mostRecentlyUpdated\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\b \x01(\tR\aorderBy\x12\x12\n" +
	"\x04skip\x18\t \x01(\x05R\x04skip\"\xa7\x01\n" +
	"\aAPKList\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.chainguard.platform.apk.APKPackageR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\"\xb6\x04\n" +
	"\n" +
	"APKPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bchecksum\x18\n" +
	" \x01(\fR\bchecksum\x12!\n" +
	"\fpackage_name\x18\v \x01(\tR\vpackageName\x12\x18\n" +
	"\aversion\x18\f \x01(\tR\aversion\x12\"\n" +
	"\farchitecture\x18\r \x01(\tR\farchitecture\x12\x12\n" +
	"\x04size\x18\x0e \x01(\x04R\x04size\x12%\n" +
	"\x0einstalled_size\x18\x0f \x01(\x04R\rinstalledSize\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x11 \x01(\tR\x03url\x12\x18\n" +
	"\alicense\x18\x12 \x01(\tR\alicense\x12\x16\n" +
	"\x06origin\x18\x13 \x01(\tR\x06origin\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x14 \x01(\tR\n" +
	"maintainer\x129\n" +
	"\n" +
	"build_time\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tbuildTime\x12\x1f\n" +
	"\vrepo_commit\x18\x16 \x01(\tR\n" +
	"repoCommit\x12+\n" +
	"\x11provider_priority\x18\x17 \x01(\x04R\x10providerPriority\x12\x16\n" +
	"\x06depend\x18\x18 \x03(\tR\x06depend\x12\x1a\n" +
	"\bprovides\x18\x19 \x03(\tR\bprovides\x12\x1d\n" +
	"\n" +
	"install_if\x18\x1a \x03(\tR\tinstallIf\"\x8b\x02\n" +
	"\x10APKSummaryFilter\x12:\n" +
	"\x04uidp\x18\x01 \x01(\v2&.chainguard.platform.common.UIDPFilterR\x04uidp\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\a \x01(\tR\aorderBy\x12\x12\n" +
	"\x04skip\x18\b \x01(\x05R\x04skip\"\x92\x02\n" +
	"\x11APKPackageSummary\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12$\n" +
	"\rarchitectures\x18\x03 \x01(\tR\rarchitectures\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x05 \x01(\tR\alicense\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\x129\n" +
	"\n" +
	"build_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tbuildTime\"\xbc\x01\n" +
	"\x15APKPackageSummaryList\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.chainguard.platform.apk.APKPackageSummaryR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped2\xa0\x02\n" +
	"\x03APK\x12x\n" +
	"\bListAPKs\x12\".chainguard.platform.apk.APKFilter\x1a .chainguard.platform.apk.APKList\"&\x82\xd3\xe4\x93\x02\x12\x12\x10/apk/v1/packages\x8a\xaf\xa8\xd2\x05\b\x12\x06\n" +
	"\x02\xf4\f\x10\x01\x12\x9e\x01\n" +
	"\x10ListAPKSummaries\x12).chainguard.platform.apk.APKSummaryFilter\x1a..chainguard.platform.apk.APKPackageSummaryList\"/\x82\xd3\xe4\x93\x02\x1b\x12\x19/apk/v1/package-summaries\x8a\xaf\xa8\xd2\x05\b\x12\x06\n" +
	"\x02\xf4\f\x10\x01B*Z(chainguard.dev/sdk/proto/platform/apk/v1b\x06proto3"

var (
	file_apk_platform_proto_rawDescOnce sync.Once
	file_apk_platform_proto_rawDescData []byte
)

func file_apk_platform_proto_rawDescGZIP() []byte {
	file_apk_platform_proto_rawDescOnce.Do(func() {
		file_apk_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apk_platform_proto_rawDesc), len(file_apk_platform_proto_rawDesc)))
	})
	return file_apk_platform_proto_rawDescData
}

var file_apk_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apk_platform_proto_goTypes = []any{
	(*APKFilter)(nil),             // 0: chainguard.platform.apk.APKFilter
	(*APKList)(nil),               // 1: chainguard.platform.apk.APKList
	(*APKPackage)(nil),            // 2: chainguard.platform.apk.APKPackage
	(*APKSummaryFilter)(nil),      // 3: chainguard.platform.apk.APKSummaryFilter
	(*APKPackageSummary)(nil),     // 4: chainguard.platform.apk.APKPackageSummary
	(*APKPackageSummaryList)(nil), // 5: chainguard.platform.apk.APKPackageSummaryList
	(*v1.UIDPFilter)(nil),         // 6: chainguard.platform.common.UIDPFilter
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_apk_platform_proto_depIdxs = []int32{
	6, // 0: chainguard.platform.apk.APKFilter.uidp:type_name -> chainguard.platform.common.UIDPFilter
	2, // 1: chainguard.platform.apk.APKList.items:type_name -> chainguard.platform.apk.APKPackage
	7, // 2: chainguard.platform.apk.APKPackage.build_time:type_name -> google.protobuf.Timestamp
	6, // 3: chainguard.platform.apk.APKSummaryFilter.uidp:type_name -> chainguard.platform.common.UIDPFilter
	7, // 4: chainguard.platform.apk.APKPackageSummary.build_time:type_name -> google.protobuf.Timestamp
	4, // 5: chainguard.platform.apk.APKPackageSummaryList.items:type_name -> chainguard.platform.apk.APKPackageSummary
	0, // 6: chainguard.platform.apk.APK.ListAPKs:input_type -> chainguard.platform.apk.APKFilter
	3, // 7: chainguard.platform.apk.APK.ListAPKSummaries:input_type -> chainguard.platform.apk.APKSummaryFilter
	1, // 8: chainguard.platform.apk.APK.ListAPKs:output_type -> chainguard.platform.apk.APKList
	5, // 9: chainguard.platform.apk.APK.ListAPKSummaries:output_type -> chainguard.platform.apk.APKPackageSummaryList
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apk_platform_proto_init() }
func file_apk_platform_proto_init() {
	if File_apk_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apk_platform_proto_rawDesc), len(file_apk_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apk_platform_proto_goTypes,
		DependencyIndexes: file_apk_platform_proto_depIdxs,
		MessageInfos:      file_apk_platform_proto_msgTypes,
	}.Build()
	File_apk_platform_proto = out.File
	file_apk_platform_proto_goTypes = nil
	file_apk_platform_proto_depIdxs = nil
}
