// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: chainguard/platform/billing/v2beta1/billing.proto

package v2beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_CreateCheckoutSession_FullMethodName = "/chainguard.platform.billing.v2beta1.BillingService/CreateCheckoutSession"
	BillingService_CreatePortalSession_FullMethodName   = "/chainguard.platform.billing.v2beta1.BillingService/CreatePortalSession"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingService starts self-serve plan purchases and card management for an
// organization. Payment pages are hosted by the payment provider; no card data
// passes through this API.
type BillingServiceClient interface {
	// CreateCheckoutSession opens a hosted checkout page where an owner of a
	// Starter organization enters a card to upgrade the organization to the
	// Team plan. The organization is upgraded once the first invoice is paid,
	// not when this call returns.
	// (-- api-linter: core::0133::http-body=disabled
	//     aip.dev/not-precedent: the session is built entirely by the server
	//     from the organization, so the request carries no resource. --)
	CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CheckoutSession, error)
	// CreatePortalSession opens a hosted page where an owner of a Team
	// organization updates the card the organization pays with.
	// (-- api-linter: core::0133::http-body=disabled
	//     aip.dev/not-precedent: the session is built entirely by the server
	//     from the organization, so the request carries no resource. --)
	CreatePortalSession(ctx context.Context, in *CreatePortalSessionRequest, opts ...grpc.CallOption) (*PortalSession, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CheckoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckoutSession)
	err := c.cc.Invoke(ctx, BillingService_CreateCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreatePortalSession(ctx context.Context, in *CreatePortalSessionRequest, opts ...grpc.CallOption) (*PortalSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortalSession)
	err := c.cc.Invoke(ctx, BillingService_CreatePortalSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// BillingService starts self-serve plan purchases and card management for an
// organization. Payment pages are hosted by the payment provider; no card data
// passes through this API.
type BillingServiceServer interface {
	// CreateCheckoutSession opens a hosted checkout page where an owner of a
	// Starter organization enters a card to upgrade the organization to the
	// Team plan. The organization is upgraded once the first invoice is paid,
	// not when this call returns.
	// (-- api-linter: core::0133::http-body=disabled
	//     aip.dev/not-precedent: the session is built entirely by the server
	//     from the organization, so the request carries no resource. --)
	CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CheckoutSession, error)
	// CreatePortalSession opens a hosted page where an owner of a Team
	// organization updates the card the organization pays with.
	// (-- api-linter: core::0133::http-body=disabled
	//     aip.dev/not-precedent: the session is built entirely by the server
	//     from the organization, so the request carries no resource. --)
	CreatePortalSession(context.Context, *CreatePortalSessionRequest) (*PortalSession, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CheckoutSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCheckoutSession not implemented")
}
func (UnimplementedBillingServiceServer) CreatePortalSession(context.Context, *CreatePortalSessionRequest) (*PortalSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePortalSession not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_CreateCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateCheckoutSession(ctx, req.(*CreateCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreatePortalSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePortalSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreatePortalSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreatePortalSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreatePortalSession(ctx, req.(*CreatePortalSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.platform.billing.v2beta1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCheckoutSession",
			Handler:    _BillingService_CreateCheckoutSession_Handler,
		},
		{
			MethodName: "CreatePortalSession",
			Handler:    _BillingService_CreatePortalSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainguard/platform/billing/v2beta1/billing.proto",
}
