issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:chainguard-dev/mono:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/mono/.github/workflows/export-sdk.yaml

permissions:
  contents: write
  pull_requests: write
