// Copyright 2026 Chainguard, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: argos_vex.platform.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArgosVEX_GetDocument_FullMethodName = "/chainguard.platform.argos.ArgosVEX/GetDocument"
	ArgosVEX_Dump_FullMethodName        = "/chainguard.platform.argos.ArgosVEX/Dump"
)

// ArgosVEXClient is the client API for ArgosVEX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArgosVEX is the customer-facing surface for the OpenVEX feed derived from
// the Private OSV shared corpus. Documents are customer-blind: all members
// holding CAP_ARGOS_OSV_READ see the same document set; the feed is a
// re-encoding of data that capability already grants. All RPCs here are
// unscoped: the server implementation MUST reject callers with zero
// authorized scopes as its first action (see api-impl argos core).
type ArgosVEXClient interface {
	// GetDocument returns the per-package OpenVEX document, verbatim as
	// published to the feed.
	GetDocument(ctx context.Context, in *GetVEXDocumentRequest, opts ...grpc.CallOption) (*VEXDocument, error)
	// Dump streams the full feed archive (tar.gz). The first frame is
	// metadata; subsequent frames are chunks. Chunk size is server-chosen,
	// < 4MB.
	Dump(ctx context.Context, in *DumpVEXRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DumpVEXResponse], error)
}

type argosVEXClient struct {
	cc grpc.ClientConnInterface
}

func NewArgosVEXClient(cc grpc.ClientConnInterface) ArgosVEXClient {
	return &argosVEXClient{cc}
}

func (c *argosVEXClient) GetDocument(ctx context.Context, in *GetVEXDocumentRequest, opts ...grpc.CallOption) (*VEXDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VEXDocument)
	err := c.cc.Invoke(ctx, ArgosVEX_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *argosVEXClient) Dump(ctx context.Context, in *DumpVEXRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DumpVEXResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArgosVEX_ServiceDesc.Streams[0], ArgosVEX_Dump_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DumpVEXRequest, DumpVEXResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArgosVEX_DumpClient = grpc.ServerStreamingClient[DumpVEXResponse]

// ArgosVEXServer is the server API for ArgosVEX service.
// All implementations must embed UnimplementedArgosVEXServer
// for forward compatibility.
//
// ArgosVEX is the customer-facing surface for the OpenVEX feed derived from
// the Private OSV shared corpus. Documents are customer-blind: all members
// holding CAP_ARGOS_OSV_READ see the same document set; the feed is a
// re-encoding of data that capability already grants. All RPCs here are
// unscoped: the server implementation MUST reject callers with zero
// authorized scopes as its first action (see api-impl argos core).
type ArgosVEXServer interface {
	// GetDocument returns the per-package OpenVEX document, verbatim as
	// published to the feed.
	GetDocument(context.Context, *GetVEXDocumentRequest) (*VEXDocument, error)
	// Dump streams the full feed archive (tar.gz). The first frame is
	// metadata; subsequent frames are chunks. Chunk size is server-chosen,
	// < 4MB.
	Dump(*DumpVEXRequest, grpc.ServerStreamingServer[DumpVEXResponse]) error
	mustEmbedUnimplementedArgosVEXServer()
}

// UnimplementedArgosVEXServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArgosVEXServer struct{}

func (UnimplementedArgosVEXServer) GetDocument(context.Context, *GetVEXDocumentRequest) (*VEXDocument, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedArgosVEXServer) Dump(*DumpVEXRequest, grpc.ServerStreamingServer[DumpVEXResponse]) error {
	return status.Error(codes.Unimplemented, "method Dump not implemented")
}
func (UnimplementedArgosVEXServer) mustEmbedUnimplementedArgosVEXServer() {}
func (UnimplementedArgosVEXServer) testEmbeddedByValue()                  {}

// UnsafeArgosVEXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArgosVEXServer will
// result in compilation errors.
type UnsafeArgosVEXServer interface {
	mustEmbedUnimplementedArgosVEXServer()
}

func RegisterArgosVEXServer(s grpc.ServiceRegistrar, srv ArgosVEXServer) {
	// If the following call panics, it indicates UnimplementedArgosVEXServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArgosVEX_ServiceDesc, srv)
}

func _ArgosVEX_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVEXDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArgosVEXServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArgosVEX_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArgosVEXServer).GetDocument(ctx, req.(*GetVEXDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArgosVEX_Dump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpVEXRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArgosVEXServer).Dump(m, &grpc.GenericServerStream[DumpVEXRequest, DumpVEXResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArgosVEX_DumpServer = grpc.ServerStreamingServer[DumpVEXResponse]

// ArgosVEX_ServiceDesc is the grpc.ServiceDesc for ArgosVEX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArgosVEX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainguard.platform.argos.ArgosVEX",
	HandlerType: (*ArgosVEXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocument",
			Handler:    _ArgosVEX_GetDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dump",
			Handler:       _ArgosVEX_Dump_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "argos_vex.platform.proto",
}
